project:
  type: book
  output-dir: docs

execute: 
  freeze: auto

book:
  title: "Introduction to Generalized Linear Modeling"
  reader-mode: true
  page-footer: 
    left: |
      Introduction to Generalized Linear Modeling was written by
      Aaron Matthew Simmons and Jeffrey M. Girard.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  cover-image: "cover.png"
  favicon: "cover.png"
  site-url: https://affcomlab.github.io/learn-glms/
  repo-url: https://www.github.com/affcomlab/learn-glms/
  repo-branch: main
  repo-actions: [issue]
  chapters:
    - index.qmd
    - intro.qmd
    - regression-review.qmd
    - linear-models.qmd
    - summary.qmd
    - references.qmd
    

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-link: true
    author-meta: "Aaron Matthew Simmons and Jeffrey M. Girard"

website:
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Preface"
        href: index.qmd
      - section: "Introduction"
        href: intro.qmd
        contents:
          - regression-review.qmd
          - linear-models.qmd
      - section: "Generalized Linear Models"
        contents:
          - summary.qmd
      - references.qmd


