<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Aaron Matthew Simmons and Jeffrey M. Girard">

<title>Introduction to Generalized Linear Modeling - 3&nbsp; Binary Regression</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./linear-models.html" rel="next">
<link href="./regression-review.html" rel="prev">
<link href="./cover.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating nav-fixed slimcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Introduction to Generalized Linear Modeling</span>
    </a>
  </div>
        <div class="quarto-navbar-tools ms-auto">
    <a href="https://www.github.com/affcomlab/learn-glms/" rel="" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
          <div id="quarto-search" class="" title="Search"></div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./binary-regression.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Binary Regression</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./regression-review.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Regression Recap</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./binary-regression.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Binary Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./linear-models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Linear models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./summary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Summary</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Appendix</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#why-binary-regression" id="toc-why-binary-regression" class="nav-link active" data-scroll-target="#why-binary-regression"><span class="header-section-number">3.1</span> Why Binary Regression?</a>
  <ul class="collapse">
  <li><a href="#shape-of-residuals" id="toc-shape-of-residuals" class="nav-link" data-scroll-target="#shape-of-residuals"><span class="header-section-number">3.1.1</span> Shape of Residuals</a></li>
  <li><a href="#continuous-and-normally-distributed-outcome" id="toc-continuous-and-normally-distributed-outcome" class="nav-link" data-scroll-target="#continuous-and-normally-distributed-outcome"><span class="header-section-number">3.1.2</span> Continuous and Normally Distributed Outcome</a></li>
  </ul></li>
  <li><a href="#comparing-simple-regression-to-simple-binary-regression" id="toc-comparing-simple-regression-to-simple-binary-regression" class="nav-link" data-scroll-target="#comparing-simple-regression-to-simple-binary-regression"><span class="header-section-number">3.2</span> Comparing Simple Regression to Simple Binary Regression</a>
  <ul class="collapse">
  <li><a href="#link-function-logit" id="toc-link-function-logit" class="nav-link" data-scroll-target="#link-function-logit"><span class="header-section-number">3.2.1</span> Link function: logit</a></li>
  <li><a href="#probability-odds-and-log-odds" id="toc-probability-odds-and-log-odds" class="nav-link" data-scroll-target="#probability-odds-and-log-odds"><span class="header-section-number">3.2.2</span> Probability, Odds, and Log Odds</a></li>
  </ul></li>
  <li><a href="#data-demonstration" id="toc-data-demonstration" class="nav-link" data-scroll-target="#data-demonstration"><span class="header-section-number">3.3</span> Data Demonstration</a></li>
  <li><a href="#loading-the-packages-and-reading-in-data" id="toc-loading-the-packages-and-reading-in-data" class="nav-link" data-scroll-target="#loading-the-packages-and-reading-in-data"><span class="header-section-number">3.4</span> Loading the Packages and Reading in Data</a></li>
  <li><a href="#prepare-data-exploratory-data-analysis" id="toc-prepare-data-exploratory-data-analysis" class="nav-link" data-scroll-target="#prepare-data-exploratory-data-analysis"><span class="header-section-number">3.5</span> Prepare Data / Exploratory Data Analysis</a>
  <ul class="collapse">
  <li><a href="#plotting-a-binary-outcome" id="toc-plotting-a-binary-outcome" class="nav-link" data-scroll-target="#plotting-a-binary-outcome"><span class="header-section-number">3.5.1</span> Plotting a binary outcome</a></li>
  </ul></li>
  <li><a href="#fitting-the-general-linear-model-not-recommended" id="toc-fitting-the-general-linear-model-not-recommended" class="nav-link" data-scroll-target="#fitting-the-general-linear-model-not-recommended"><span class="header-section-number">4</span> Fitting the General Linear Model (Not Recommended)</a></li>
  <li><a href="#fitting-the-logistic-regression-models" id="toc-fitting-the-logistic-regression-models" class="nav-link" data-scroll-target="#fitting-the-logistic-regression-models"><span class="header-section-number">5</span> Fitting the Logistic Regression Models</a>
  <ul class="collapse">
  <li><a href="#intercept-only-model" id="toc-intercept-only-model" class="nav-link" data-scroll-target="#intercept-only-model"><span class="header-section-number">5.1</span> Intercept-Only Model</a>
  <ul class="collapse">
  <li><a href="#probability-odds-and-log-odds-1" id="toc-probability-odds-and-log-odds-1" class="nav-link" data-scroll-target="#probability-odds-and-log-odds-1"><span class="header-section-number">5.1.1</span> Probability, Odds, and Log Odds</a></li>
  <li><a href="#fitting-the-intercept-only-model" id="toc-fitting-the-intercept-only-model" class="nav-link" data-scroll-target="#fitting-the-intercept-only-model"><span class="header-section-number">5.1.2</span> Fitting the Intercept-Only Model</a></li>
  <li><a href="#paramter-table-interpretation" id="toc-paramter-table-interpretation" class="nav-link" data-scroll-target="#paramter-table-interpretation"><span class="header-section-number">5.1.3</span> Paramter Table Interpretation</a></li>
  </ul></li>
  <li><a href="#one-continuous-predictor" id="toc-one-continuous-predictor" class="nav-link" data-scroll-target="#one-continuous-predictor"><span class="header-section-number">5.2</span> One Continuous Predictor</a>
  <ul class="collapse">
  <li><a href="#parameter-table-interpretation-log-odds" id="toc-parameter-table-interpretation-log-odds" class="nav-link" data-scroll-target="#parameter-table-interpretation-log-odds"><span class="header-section-number">5.2.1</span> Parameter Table Interpretation (Log-odds)</a></li>
  <li><a href="#parameter-table-interpretation-odds" id="toc-parameter-table-interpretation-odds" class="nav-link" data-scroll-target="#parameter-table-interpretation-odds"><span class="header-section-number">5.2.2</span> Parameter Table Interpretation (Odds)</a></li>
  <li><a href="#predicted-probability" id="toc-predicted-probability" class="nav-link" data-scroll-target="#predicted-probability"><span class="header-section-number">5.2.3</span> Predicted Probability</a></li>
  </ul></li>
  <li><a href="#two-continuous-predictors" id="toc-two-continuous-predictors" class="nav-link" data-scroll-target="#two-continuous-predictors"><span class="header-section-number">5.3</span> Two Continuous Predictors</a>
  <ul class="collapse">
  <li><a href="#parameter-table-interpretation-log-odds-1" id="toc-parameter-table-interpretation-log-odds-1" class="nav-link" data-scroll-target="#parameter-table-interpretation-log-odds-1"><span class="header-section-number">5.3.1</span> Parameter Table Interpretation (Log-odds)</a></li>
  <li><a href="#parameter-table-interpretation-odds-1" id="toc-parameter-table-interpretation-odds-1" class="nav-link" data-scroll-target="#parameter-table-interpretation-odds-1"><span class="header-section-number">5.3.2</span> Parameter Table Interpretation (Odds)</a></li>
  <li><a href="#predicted-probability-1" id="toc-predicted-probability-1" class="nav-link" data-scroll-target="#predicted-probability-1"><span class="header-section-number">5.3.3</span> Predicted Probability</a></li>
  </ul></li>
  <li><a href="#one-dummy-coded-predictor" id="toc-one-dummy-coded-predictor" class="nav-link" data-scroll-target="#one-dummy-coded-predictor"><span class="header-section-number">5.4</span> One Dummy Coded Predictor</a>
  <ul class="collapse">
  <li><a href="#parameter-table-interpretation-log-odds-2" id="toc-parameter-table-interpretation-log-odds-2" class="nav-link" data-scroll-target="#parameter-table-interpretation-log-odds-2"><span class="header-section-number">5.4.1</span> Parameter Table Interpretation (Log-odds)</a></li>
  <li><a href="#estimating-means-and-plots" id="toc-estimating-means-and-plots" class="nav-link" data-scroll-target="#estimating-means-and-plots"><span class="header-section-number">5.4.2</span> Estimating means and plots</a></li>
  <li><a href="#parameter-table-interpretation-odds-2" id="toc-parameter-table-interpretation-odds-2" class="nav-link" data-scroll-target="#parameter-table-interpretation-odds-2"><span class="header-section-number">5.4.3</span> Parameter Table Interpretation (Odds)</a></li>
  <li><a href="#predicted-probability-2" id="toc-predicted-probability-2" class="nav-link" data-scroll-target="#predicted-probability-2"><span class="header-section-number">5.4.4</span> Predicted Probability</a></li>
  </ul></li>
  <li><a href="#one-dummy-coded-and-one-continuous-predictor" id="toc-one-dummy-coded-and-one-continuous-predictor" class="nav-link" data-scroll-target="#one-dummy-coded-and-one-continuous-predictor"><span class="header-section-number">5.5</span> One Dummy Coded and One Continuous Predictor</a>
  <ul class="collapse">
  <li><a href="#paramter-table-interpretation-log-odds" id="toc-paramter-table-interpretation-log-odds" class="nav-link" data-scroll-target="#paramter-table-interpretation-log-odds"><span class="header-section-number">5.5.1</span> Paramter Table Interpretation (Log-odds)</a></li>
  <li><a href="#parameter-table-interpretation-odds-3" id="toc-parameter-table-interpretation-odds-3" class="nav-link" data-scroll-target="#parameter-table-interpretation-odds-3"><span class="header-section-number">5.5.2</span> Parameter Table Interpretation (Odds)</a></li>
  <li><a href="#predicted-probabilities" id="toc-predicted-probabilities" class="nav-link" data-scroll-target="#predicted-probabilities"><span class="header-section-number">5.5.3</span> Predicted Probabilities</a></li>
  <li><a href="#estimating-means-and-plots-1" id="toc-estimating-means-and-plots-1" class="nav-link" data-scroll-target="#estimating-means-and-plots-1"><span class="header-section-number">5.5.4</span> Estimating Means and Plots</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#assumptions" id="toc-assumptions" class="nav-link" data-scroll-target="#assumptions"><span class="header-section-number">6</span> Assumptions</a></li>
  </ul>
<div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://www.github.com/affcomlab/learn-glms/issues/new" class="toc-action">Report an issue</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Binary Regression</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p>We start our first look at GLMs with binary regression. Here, we consider when binary regression, specifically <i>logistic regression</i>, is more appropriate than a regular (general linear) regression. We will also fit toy data and interpret the results.</p>
<section id="why-binary-regression" class="level2 page-columns page-full" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="why-binary-regression"><span class="header-section-number">3.1</span> Why Binary Regression?</h2>
<p>When the outcome is a binary variable, or when there are only <b>two</b> possible outcomes, there are two essential problems with using the general linear model (e.g., the regular <code>lm()</code> function) . The first essential problem is due to the non-normal shape of the residuals. The second essential problem is that the outcome variable is not continuous and normally distributed. Both problems contribute to general linear models being biased and making impossible predictions.</p>
<p>Binary regression is a general term that encompasses specific models such as <i>logistic regression</i> and <i>probit regression</i>. It is a way to analyze binary data and hold the assumptions of linear models more true. We will focus on logistic regression in this module.</p>

<div class="no-row-height column-margin column-container"><div class="">
<p><b>Terms</b></p>
</div><div class="">
<p>Binary Regression: A general term for models for when the outcome variable has only two possible outcomes. <br></p>
</div><div class="">
<p>Logistic Regression: A specific binary regression model which uses the logistic function as the link function. <br></p>
</div><div class="">
<p>Probit Regression: A specific binary regression model which uses the probit function as the link function. <br></p>
</div><div class="">
<p>Link Function: A function that transforms the outcome variable into a continuous and unbounded variable. It is a key aspect of generalized linear models.</p>
</div></div>



<section id="shape-of-residuals" class="level3" data-number="3.1.1">
<h3 data-number="3.1.1" class="anchored" data-anchor-id="shape-of-residuals"><span class="header-section-number">3.1.1</span> Shape of Residuals</h3>
<p>The general linear model assumes that residuals, or the differences between the observed and predicted values of data, are <b>normally distributed</b>. If the residuals are not normally distributed, the model will not make valid inferences or ** (possibly)** predictions.</p>
</section>
<section id="continuous-and-normally-distributed-outcome" class="level3" data-number="3.1.2">
<h3 data-number="3.1.2" class="anchored" data-anchor-id="continuous-and-normally-distributed-outcome"><span class="header-section-number">3.1.2</span> Continuous and Normally Distributed Outcome</h3>
<p>Since the outcome variable is binary, a quick histogram plot will show that it is not continuous (i.e., it is discrete). This is a scourge for the general linear model since it assumes continuous and normally distributed outcomes, and it will predict both intermediate states/values between the two possible outcomes <b>and</b> states/values above and below the two possible outcomes. For example, if 0 = Alive, and 1 = Dead, then the general linear model may predict a value between 0 and 1 (somewhere between alive and dead), or values below 0 and above 1 (so less alive and more dead?).</p>
<p>Therefore, to model a binary outcome using the machinery of linear modeling, we need to <b>transform</b> the outcome variable to a continuous and normally distributed outcome. We do that with what’s called a <i>link function</i>. In other words, the link function will take the binary outcome variable and transform it to a continuous and more normally distributed outcome variable. By using a link function, we move from the general linear model to a <i>generalized linear model</i>. See more about link functions in the next section.</p>
<p>Before we fit our first binary regression, let’s take a look at what is actually happening and why the <b>generalized</b> linear model is similar, but different, to the general linear model.</p>
</section>
</section>
<section id="comparing-simple-regression-to-simple-binary-regression" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="comparing-simple-regression-to-simple-binary-regression"><span class="header-section-number">3.2</span> Comparing Simple Regression to Simple Binary Regression</h2>
<p>In simple regression, we are predicting the outcome (<span class="math inline">\(y_{{i}}\)</span>) with a linear (additive) combination of an intercept (<span class="math inline">\(\beta_0\)</span>) and one predictor variable (<span class="math inline">\(x\)</span>).</p>
<p><span class="math display">\[ \hat{y}_{{i}} = \beta_0 + \beta_1 x \]</span> In simple binary regression, we are <b>still</b> predicting an outcome with a linear (additive) combination of intercept and one predictor variable. We use the term “simple” only because we have one predictor variable in this case.</p>
<p><span class="math display">\[ \hat{\eta}_{i} = \beta_0 + \beta_1 x \]</span></p>
<p>Note that the linearly additive feature that both simple regression and simple binary regression share is what makes these models related and interpretable.</p>
<p>The main difference is why, in simple binary regression, did the outcome variable change from <span class="math inline">\(y_{{i}}\)</span> to <span class="math inline">\(\eta_{i}\)</span>? Because in binary regression, we are no longer predicting the binary outcome event (e.g., “yes/no”). Usually (but not always) we are predicting the <b> probability </b> of the binary event occurring. This means that <span class="math inline">\(\eta_{i}\)</span> is a probability that is bounded between 0 (“no” event) and 1 (“yes” event).</p>
<p>The next section will relate <span class="math inline">\(y_{\hat{i}}\)</span> to <span class="math inline">\(\eta_{i}\)</span>.</p>
<section id="link-function-logit" class="level3" data-number="3.2.1">
<h3 data-number="3.2.1" class="anchored" data-anchor-id="link-function-logit"><span class="header-section-number">3.2.1</span> Link function: logit</h3>
<p>We need to make a connection between the probability of an event (<span class="math inline">\(\eta_{i}\)</span>) to an event outcome (<span class="math inline">\(y_{{i}}\)</span>). This is possible in this way:</p>
<ul>
<li><p>The outcome <span class="math inline">\(y_{{i}}\)</span> for i = 1,…,<span class="math inline">\(n\)</span> events takes values zero or one with the probability of a 1 = <span class="math inline">\(p_i\)</span></p></li>
<li><p>In other words, <span class="math inline">\(P(Y_i = 1)\)</span> = <span class="math inline">\(p_i\)</span>, or P is the probabilty of a 1 (e.g., “yes” happening).</p></li>
</ul>
<p>That is all just setup to define <span class="math inline">\(\eta_{i}\)</span>.</p>
<ul>
<li><span class="math inline">\(\eta_{i}= g(p_i)\)</span></li>
</ul>
<p>The variable <span class="math inline">\(g\)</span> is our “link function”. In this case, it is a function that transforms a probability (<span class="math inline">\(p_i\)</span>) into our <span class="math inline">\(\eta_{i}\)</span>. Therefore, we are trying to find the probability of an event occurring.</p>
<p>In binary regression, our <span class="math inline">\(g\)</span> is the “logit function”, which is defined as:</p>
<p><span class="math display">\[ \eta = log(p/(1-p)) \]</span> or, equivalently,</p>
<p><span class="math display">\[ p = e^\eta/ (1 + e^\eta) \]</span></p>
<p>When we use the logit link function with a linear predictor, we now can call this <i>“logistic regression”</i>.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Takeaway: Link Functions">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Takeaway: Link Functions
</div>
</div>
<div class="callout-body-container callout-body">
<p>When we use GLMs, we will be using many different link functions depending on the data. In the case of binary/logistic regression, all this function is trying to do is relate our linear predictors to a response outcome that is continuous and between some bounds (like 0 and 1). This is because if we <b>did not</b> do this, we are using the linear predictors to predictor some value that is continuous when it is <b>not</b> technically continuous, and the predictions can be out of bounds (so, when an event “yes” = 1, then the model can spit out a value like 1.53, even though this event is unreasonable). We also find that when using the appropriate link function, other problems, like the shape of residuals, gets fixed!</p>
</div>
</div>
</section>
<section id="probability-odds-and-log-odds" class="level3" data-number="3.2.2">
<h3 data-number="3.2.2" class="anchored" data-anchor-id="probability-odds-and-log-odds"><span class="header-section-number">3.2.2</span> Probability, Odds, and Log Odds</h3>
<p>When working with logistic regression, we have to be familiar with the model’s units, or frame of reference for its parameter estimates. When logistic regression models estimated, they are usually presented in log-odds, but, as we will see now, it is fairly straightforward to transform our units from log-odds to odds to probability.</p>
<p>Note that we are doing these calculations here by hand solely as an exercise to familiarize ourselves with these units. This is not actually required when running logistic regressions. Indeed, like with <code>lm()</code>, we will be given results tables which calculate all of these for us.</p>
<p>As an example, imagine flipping a coin 100 times. As an arbitrary decision, let’s consider the results of this binary event that when a coin lands on Heads, it is a Success. And when it lands on Tails, it is a failure. In this example, it lands Heads 60 times out of 100.</p>
<p><u>Probability</u> The probability of landing a head is:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>p_heads <span class="ot">&lt;-</span> <span class="dv">60</span><span class="sc">/</span>(<span class="dv">60</span><span class="sc">+</span><span class="dv">40</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>p_heads</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6</code></pre>
</div>
</div>
<p>Notice that the probability is a proportion/ratio of Heads out of the total number of coin flips.</p>
<p><u>Odds</u></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>o_heads <span class="ot">&lt;-</span> p_heads<span class="sc">/</span>(<span class="dv">1</span> <span class="sc">-</span> p_heads)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>o_heads</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.5</code></pre>
</div>
</div>
<p>Odds is simply another way of describing probability. It is also a ratio, like probability, but essentially with odds you can have some way to describe the relative likelihood of the event occurring versus not occurring. For example, if the probability of an event occurring is 0.75 or 75% likely, its odds of happening is “3 to 1”, or it is 3 times more likely that the event will occur relative to it not occurring.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fl">0.75</span><span class="sc">/</span>(<span class="dv">1</span><span class="fl">-0.75</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3</code></pre>
</div>
</div>
<p>In the case of the data, the odds for flipping a Heads is 1.50.</p>
<p>Working with odds can be challenging at first but there is a rule of thumb to follow. Imagine if <span class="math inline">\(p=.50\)</span>, then it is 50% chance of an event occurring or not occurring. Then, when we convert this to odds, then <span class="math inline">\(odds= .50/.50 =1\)</span>. So, <b> if you get an odds value that equals 1 </b>, then both events are equally likely, and if it less than 1, then it is less likely for an event to occur, and if it is more than one, it is more likely for an event to occur.</p>
<p>It seems like flipping Heads 60 times out of 100 is more likely with a value of 1.50</p>
<p><u>Log-Odds</u></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>log_heads <span class="ot">&lt;-</span> <span class="fu">log</span>(o_heads)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>log_heads</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4054651</code></pre>
</div>
</div>
<p>You might wonder why we make an effort to convert odds to log-odds. Well, again, it is because it our logistic link function that takes our outcome variable and transforms it into a continuous and bounded outcome variable so that it can work well with linearly additive predictors variables.</p>
<p>Just like with odds, there we can consider a rule of thumb where if <span class="math inline">\(odds=1\)</span> then the $log odds=ln(1)=0 $. So, if we obtain a log-odds value of 0, then the event is equally likely to occur or not occur.</p>
<p>Our data shows a log-odds of <span class="math inline">\(0.41\)</span>, which means it is more than 0, so we can see that it is more likely (in terms of log-odds) for someone to flip a Head than a Tail.</p>
</section>
</section>
<section id="data-demonstration" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="data-demonstration"><span class="header-section-number">3.3</span> Data Demonstration</h2>
<p>The data for this chapter consists of some records of passengers on the Titanic. The question we will ask and answer with binary regression is if the amount of fare contributed in some way to the survival of passengers. Since <code>survived</code> is a binary outcome (yes or no), this relationship is best assessed with binary regression.</p>
<ul>
<li>Data: <a href="./titanic.csv" download=""> titanic.csv </a></li>
</ul>
</section>
<section id="loading-the-packages-and-reading-in-data" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="loading-the-packages-and-reading-in-data"><span class="header-section-number">3.4</span> Loading the Packages and Reading in Data</h2>
<p>In addition to our usual packages (<code>tidyverse</code>, <code>easystats</code>, and <code>ggeffects</code>), we will also need to load <code>DHARMa</code> and <code>qqplotr</code> in order to make our plots for our binary regression models.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Load packages</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(easystats)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggeffects)</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(DHARMa)</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(qqplotr)</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a><span class="do">## Read in data from file</span></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>titanic_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"titanic.csv"</span>)</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>titanic_data</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 887 × 5
   sex      age class  fare survived
   &lt;chr&gt;  &lt;dbl&gt; &lt;chr&gt; &lt;dbl&gt; &lt;chr&gt;   
 1 male      22 3rd    7.25 no      
 2 female    38 1st   71.3  yes     
 3 female    26 3rd    7.92 yes     
 4 female    35 1st   53.1  yes     
 5 male      35 3rd    8.05 no      
 6 male      27 3rd    8.46 no      
 7 male      54 1st   51.9  no      
 8 male       2 3rd   21.1  no      
 9 female    27 3rd   11.1  yes     
10 female    14 2nd   30.1  yes     
# ℹ 877 more rows</code></pre>
</div>
</div>
<p>This data shows records for 877 passengers on the Titanic.</p>
<p>Here’s a table of our variables in this dataset:</p>
<table class="table">
<colgroup>
<col style="width: 18%">
<col style="width: 46%">
<col style="width: 16%">
<col style="width: 18%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th style="text-align: left;">Description</th>
<th style="text-align: right;">Values</th>
<th style="text-align: center;">Measurement</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>sex</code></td>
<td style="text-align: left;">Male or Female</td>
<td style="text-align: right;">Characters</td>
<td style="text-align: center;">Nominal</td>
</tr>
<tr class="even">
<td><code>age</code></td>
<td style="text-align: left;">Age of Passenger</td>
<td style="text-align: right;">Double</td>
<td style="text-align: center;">Scale</td>
</tr>
<tr class="odd">
<td><code>class</code></td>
<td style="text-align: left;">Category of Passenger Accommodation</td>
<td style="text-align: right;">Characters</td>
<td style="text-align: center;">Nominal</td>
</tr>
<tr class="even">
<td><code>fare</code></td>
<td style="text-align: left;">Cost of fare</td>
<td style="text-align: right;">Double</td>
<td style="text-align: center;">Scale</td>
</tr>
<tr class="odd">
<td><code>survived</code></td>
<td style="text-align: left;">“Yes” or “No” if survived</td>
<td style="text-align: right;">Characters</td>
<td style="text-align: center;">Nominal</td>
</tr>
</tbody>
</table>
</section>
<section id="prepare-data-exploratory-data-analysis" class="level2" data-number="3.5">
<h2 data-number="3.5" class="anchored" data-anchor-id="prepare-data-exploratory-data-analysis"><span class="header-section-number">3.5</span> Prepare Data / Exploratory Data Analysis</h2>
<p>In order to use the <code>survived</code> variable in our analyses, we need to re-code the outcomes as integer numbers. Here, we will use the <code>mutate()</code> function from the <code>dplyr</code> package (which is a package that automatically loaded with <code>tidyverse</code>) to add a new column to our data which re-codes “Yes” = 1 and “No” = 0.</p>
<p>Note that our choice of “Yes” = 1 and “No” = 0 is completely arbitrary. We could have just easily switched the coding scheme. However, it is important to understand that when “Yes” = 1 and “No” = 0, our model is predicting the likelihood of survival, and if it was the other way around (when Yes = 0 and No = 1), our model would be predicting the likelihood of not-surviving.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Prepare the data for analysis</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>titanic2 <span class="ot">&lt;-</span> </span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  titanic_data <span class="sc">|&gt;</span> </span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">survived_b =</span> <span class="fu">case_match</span>(</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>      survived, </span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>      <span class="st">"no"</span> <span class="sc">~</span> <span class="dv">0</span>,</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>      <span class="st">"yes"</span> <span class="sc">~</span> <span class="dv">1</span></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>titanic2 <span class="co">#print</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 887 × 6
   sex      age class  fare survived survived_b
   &lt;chr&gt;  &lt;dbl&gt; &lt;chr&gt; &lt;dbl&gt; &lt;chr&gt;         &lt;dbl&gt;
 1 male      22 3rd    7.25 no                0
 2 female    38 1st   71.3  yes               1
 3 female    26 3rd    7.92 yes               1
 4 female    35 1st   53.1  yes               1
 5 male      35 3rd    8.05 no                0
 6 male      27 3rd    8.46 no                0
 7 male      54 1st   51.9  no                0
 8 male       2 3rd   21.1  no                0
 9 female    27 3rd   11.1  yes               1
10 female    14 2nd   30.1  yes               1
# ℹ 877 more rows</code></pre>
</div>
</div>
<p>Re-coding these strings/characters into discrete numbers is important for the model’s mathematics to work.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="mutate() and data-wrangling">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
mutate() and data-wrangling
</div>
</div>
<div class="callout-body-container callout-body">
<p><code>mutate()</code> is a function from <code>dplyr</code> that adds a column to the dataframe (the object that holds the data). This isn’t the only way to accomplish our goal of re-coding <code>survived</code>, but it is a fairly elegant, easy, and straightforward way to do so. The trick is to remember that <code>mutate()</code> adds a column to the existing dataframe with the same number of rows as the existing dataframe.</p>
<p>Our choice of data-wrangling functions are open to reprisal because there are many ways in data analysis and programming to do the same thing.</p>
</div>
</div>
<section id="plotting-a-binary-outcome" class="level3" data-number="3.5.1">
<h3 data-number="3.5.1" class="anchored" data-anchor-id="plotting-a-binary-outcome"><span class="header-section-number">3.5.1</span> Plotting a binary outcome</h3>
<p>Like always, it is important to plot the data prior to fitting any model. Here, we consider if there is some sort of relationship between <code>survived_b</code> and <code>fare</code>.</p>
<p>Here, we first try a standard scatter plot. Since there are only two outcome values though, it’s hard to see any clear effect of surivavl based on <code>fare</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(titanic2, <span class="fu">aes</span>(<span class="at">x =</span> fare, <span class="at">y =</span> survived_b)) <span class="sc">+</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> mytheme</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="binary-regression_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Next, we try a box plot. The box plot helps clarify what the scatter plot can’t easily show: there seems to be some effect of fare on survival, such that the higher the fare, the more mass/points are in having survived the titanic. We will explore this relationship in our regression models.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(titanic2, <span class="fu">aes</span>(<span class="at">x =</span> fare, <span class="at">y =</span> survived)) <span class="sc">+</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span> mytheme</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="binary-regression_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="fitting-the-general-linear-model-not-recommended" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Fitting the General Linear Model (Not Recommended)</h1>
<p>Before we fit the binary regression, it would be worthwhile to try fitting the less appropriate regular general linear model. We’ll use our old friend <code>lm()</code> to assess the relationship between the outcome variable <code>survived_b</code> with the predictor variable <code>fare</code>. For more information on general linear modeling, we covered these topics in our <b>Regression Recap</b> chapter.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co">#simple linear regression</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>fitlm <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">formula =</span> survived_b <span class="sc">~</span> fare,</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> titanic2</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a><span class="fu">model_parameters</span>(fitlm) <span class="sc">|&gt;</span> <span class="fu">print_md</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 16%">
<col style="width: 17%">
<col style="width: 13%">
<col style="width: 30%">
<col style="width: 10%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Parameter</th>
<th style="text-align: center;">Coefficient</th>
<th style="text-align: center;">SE</th>
<th style="text-align: center;">95% CI</th>
<th style="text-align: center;">t(885)</th>
<th style="text-align: center;">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: center;">0.30</td>
<td style="text-align: center;">0.02</td>
<td style="text-align: center;">(0.27, 0.34)</td>
<td style="text-align: center;">16.15</td>
<td style="text-align: center;">&lt; .001</td>
</tr>
<tr class="even">
<td style="text-align: left;">fare</td>
<td style="text-align: center;">2.51e-03</td>
<td style="text-align: center;">3.18e-04</td>
<td style="text-align: center;">(1.88e-03, 3.13e-03)</td>
<td style="text-align: center;">7.88</td>
<td style="text-align: center;">&lt; .001</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>As the results show, we have a significant effect of <code>fare</code>, such that a 1 unit increase in <code>fare</code> increases the chance of survival by a small amount (0.00251 units of “survival”). Despite the challenge of interpreting what units of survival are, it is worth nothing that the regular <code>lm()</code> “worked” in that it was able to produce an estimate.</p>
<p>However, it doesn’t mean that the model is the best model to use and this is evident when we plot the predictions using the <code>predict_response()</code> function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict_response</span>(fitlm, <span class="at">terms =</span> <span class="st">"fare"</span>) <span class="sc">|&gt;</span> <span class="fu">plot</span>(<span class="at">show_data =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Data points may overlap. Use the `jitter` argument to add some amount of
  random variation to the location of data points and avoid overplotting.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="binary-regression_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Notice that although the data points are only either 0 or 1 (binary), the regression line takes intermediate values between 0 and 1, and extreme values above and below 0 and 1! For example, if a passenger paid $100, then the outcome value would be ~0.55, which is halfway between alive and dead! We can’t have passengers somewhat between alive/dead, or more or less alive/dead!</p>
<p>If that wasn’t enough to deter one from using the general linear model for binary responses, taking a look at a plot of the residuals, using <code>check_residuals()</code> <a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>, should be telling.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Check residuals</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">check_residuals</span>(fitlm) <span class="sc">|&gt;</span> <span class="fu">plot</span>() <span class="co"># looks bad</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="binary-regression_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Yikes! As you can see, the dots <b>do not</b> fall along the line. Once this or any other assumption of the general linear model are not met, this is a clear sign that parts of the model may not be trustworthy. Specifically, in this case of the non-uniformity of residuals, there is terrible violation to the model’s uncertainty estimates; therefore, while the predictions may be okay, we can (and should) do better.</p>
<p>So now, finally, we fit our first GLM.</p>
</section>
<section id="fitting-the-logistic-regression-models" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Fitting the Logistic Regression Models</h1>
<section id="intercept-only-model" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="intercept-only-model"><span class="header-section-number">5.1</span> Intercept-Only Model</h2>
<p>First, let’s fit an <i>intercept only</i> binary regression model. This means we are going to fit a model with an outcome variable and without any predictor variables. The usefulness of intercept-only models will be clear once we see the results.</p>
<p>Note first that <code>surivived_b</code> outcome variable distribution is like so:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(titanic2<span class="sc">$</span>survived_b) <span class="co"># 0 = dead, 1 = alive</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  0   1 
545 342 </code></pre>
</div>
</div>
<p>From this breakdown, we can calculate our <i>probability, odds, and log-odds</i>.</p>
<section id="probability-odds-and-log-odds-1" class="level3" data-number="5.1.1">
<h3 data-number="5.1.1" class="anchored" data-anchor-id="probability-odds-and-log-odds-1"><span class="header-section-number">5.1.1</span> Probability, Odds, and Log Odds</h3>
<p><u>Probability</u> The probabilty of survival is:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>p_survived <span class="ot">&lt;-</span> <span class="dv">342</span><span class="sc">/</span>(<span class="dv">342</span><span class="sc">+</span><span class="dv">545</span>)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>p_survived</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3855693</code></pre>
</div>
</div>
<p>Notice that the probability is a proportion/ratio of survivors out of the total number of people in the dataset. Here, it is 0.385, or a 38.5% probability of survival.</p>
<p><u>Odds</u></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>o_survived <span class="ot">&lt;-</span> p_survived<span class="sc">/</span>(<span class="dv">1</span> <span class="sc">-</span> p_survived)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>o_survived</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6275229</code></pre>
</div>
</div>
<p>Again, odds is simply another way of describing probability. It is also a ratio, like probability, but essentially with odds you can have some way to describe the relative likelihood of the event occurring versus not occurring.</p>
<p>In the case of the data, the odds for surviving the Titanic is 0.63.</p>
<p>Recall, working with odds can be challenging at first but there is a rule of thumb to follow. Imagine if <span class="math inline">\(p=.50\)</span>, then it is 50% chance of an event occurring or not occurring. Then, when we convert this to odds, then <span class="math inline">\(odds= .50/.50 =1\)</span>.</p>
<p>So, <b>if you get an odds value that equals 1</b>, then both events are equally likely, and if it less than 1, then it is less likely for an event to occur, and if it is more than one, it is more likely for an event to occur.</p>
<p><u>Log-Odds</u></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>log_odds <span class="ot">&lt;-</span> <span class="fu">log</span>(o_survived)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>log_odds</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.4659751</code></pre>
</div>
</div>
<p>Just like with odds, there we can consider a rule of thumb where if <span class="math inline">\(odds=1\)</span> then the $log odds=ln(1)=0 $. So, if we obtain a log-odds value of 0, then the event is equally likely to occur or not occur.</p>
<p>Our data shows a log-odds of <span class="math inline">\(-0.47\)</span>, which means it is less than 0, so we can see that it is less likely (in terms of log-odds) for someone survive than die in the Titanic.</p>
</section>
<section id="fitting-the-intercept-only-model" class="level3" data-number="5.1.2">
<h3 data-number="5.1.2" class="anchored" data-anchor-id="fitting-the-intercept-only-model"><span class="header-section-number">5.1.2</span> Fitting the Intercept-Only Model</h3>
<p>When we fit our binary regression, we now will use the <code>glm()</code> function which is similar to <code>lm()</code>, but has one extra input argument. Notice the “family” input argument, which requires which “family of distributions” to use and which “link function” choice.</p>
<p>For binary regression, we supply the <b>binomial</b> distribution and the <b>logit</b> link function. Let’s fit our intercept-only model and consider the model parameters.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>fit1 <span class="ot">&lt;-</span> <span class="fu">glm</span>(</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">formula =</span> survived_b <span class="sc">~</span> <span class="dv">1</span>, </span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>),</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> titanic2</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a><span class="fu">model_parameters</span>(fit1) <span class="sc">|&gt;</span> <span class="fu">print_md</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Parameter</th>
<th style="text-align: center;">Log-Odds</th>
<th style="text-align: center;">SE</th>
<th style="text-align: center;">95% CI</th>
<th style="text-align: center;">z</th>
<th style="text-align: center;">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: center;">-0.47</td>
<td style="text-align: center;">0.07</td>
<td style="text-align: center;">(-0.60, -0.33)</td>
<td style="text-align: center;">-6.75</td>
<td style="text-align: center;">&lt; .001</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="paramter-table-interpretation" class="level3" data-number="5.1.3">
<h3 data-number="5.1.3" class="anchored" data-anchor-id="paramter-table-interpretation"><span class="header-section-number">5.1.3</span> Paramter Table Interpretation</h3>
<p>The first thing to notice in our intercept only model is that the estimate for our intercept is in <b>log-odds</b>. It is <b>not</b> in raw units (unlike in regular <code>lm()</code> models). The second thing to note is that the intercept value is <span class="math inline">\(-0.47\)</span> which is equal to the log-odds we calculated by hand!</p>
<p>Therefore, the intercept only model is useful because, since there are no predictor variables, we can <b>interpret the intercept parameter as the overall log-odds of the outcome variable (defined as the log-odds of an event occurring).</b></p>
</section>
</section>
<section id="one-continuous-predictor" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="one-continuous-predictor"><span class="header-section-number">5.2</span> One Continuous Predictor</h2>
<p>Now, we investigate the question “Is there a relationship between the amount of fare and the log-odds/probability of survival?”.</p>
<p>To do this, let’s use <code>glm()</code> to fit our first simple binary regression (a logistic regreesion with one predictor variable).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>fit2 <span class="ot">&lt;-</span> <span class="fu">glm</span>(</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">formula =</span> survived_b <span class="sc">~</span> fare, </span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>), </span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> titanic2</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a><span class="do">## Print parameters in logit (i.e., log-odds) units</span></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a><span class="fu">model_parameters</span>(fit2) <span class="sc">|&gt;</span> <span class="fu">print_md</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Parameter</th>
<th style="text-align: center;">Log-Odds</th>
<th style="text-align: center;">SE</th>
<th style="text-align: center;">95% CI</th>
<th style="text-align: center;">z</th>
<th style="text-align: center;">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: center;">-0.93</td>
<td style="text-align: center;">0.10</td>
<td style="text-align: center;">(-1.12, -0.75)</td>
<td style="text-align: center;">-9.79</td>
<td style="text-align: center;">&lt; .001</td>
</tr>
<tr class="even">
<td style="text-align: left;">fare</td>
<td style="text-align: center;">0.02</td>
<td style="text-align: center;">2.23e-03</td>
<td style="text-align: center;">(0.01, 0.02)</td>
<td style="text-align: center;">6.77</td>
<td style="text-align: center;">&lt; .001</td>
</tr>
</tbody>
</table>
</div>
</div>
<section id="parameter-table-interpretation-log-odds" class="level3" data-number="5.2.1">
<h3 data-number="5.2.1" class="anchored" data-anchor-id="parameter-table-interpretation-log-odds"><span class="header-section-number">5.2.1</span> Parameter Table Interpretation (Log-odds)</h3>
<p>Again, the parameter table output from a model fit with <code>glm()</code> looks very similar to parameter table outputs from models fit with <code>lm()</code>. But there is a <b>big</b> difference – in <code>glm()</code> models, we are no longer working in the same raw units!</p>
<p>This difference is apparent in the second column of the output table: “Log-Odds”. Because we fit a logistic regression with a logit function, the parameter values are in “log-odds” unit. Technically, when <code>fare</code> is in log-odds units, we can only say:</p>
<blockquote class="blockquote">
<p>For every one 1 unit increase in <code>fare</code>, there is a 0.02 increase in the log-odds of surviving.</p>
</blockquote>
<p>Although this is technically true, it isn’t at first clear what “0.02 unit increase in log-odds of <code>fare</code>” is. It is at this point one may want to convert log-odds to probability. But before we do that, let’s interpret the <span class="math inline">\(0.02\)</span> log-odds value:</p>
<ul>
<li><p>If log-odds $ = 0.02$, then it is the case that we can say it is more likely for someone to survive the Titanic with an <b>increase</b> in the amount of paid fare.</p></li>
<li><p>This effect is also statistically significant from 0 (<span class="math inline">\(p&lt;0.001\)</span>). Remember, with log-odds, a value of 0 means it is equally likely for an event to occur or not occur.</p></li>
</ul>
</section>
<section id="parameter-table-interpretation-odds" class="level3" data-number="5.2.2">
<h3 data-number="5.2.2" class="anchored" data-anchor-id="parameter-table-interpretation-odds"><span class="header-section-number">5.2.2</span> Parameter Table Interpretation (Odds)</h3>
<p>We can easily convert log-odds to odds. Given we know that it is a positive value, we can expect the odds of surviving to be more likely and therefore above 1. In order to convert from a log-odds to odds, we just need to take the exponent of the value (because if a log-odds value of 0 is equally likely, then <span class="math inline">\(e^1 = 0\)</span> where 1 is our reference for an equally likely event in odds). Let’s practice our conversion by hand.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fl">0.02</span>) <span class="co">#convert log-odds to odds</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.020201</code></pre>
</div>
</div>
<p>Now that we are in odds, we can adjust our previous interpretation of the <code>fare</code> parameter for odds:</p>
<blockquote class="blockquote">
<p>For every one unit increase in <code>fare</code>, there is a 0.020 increase, or a 2.0% increase, in the odds of surviving.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></p>
</blockquote>
<p>Fortunately, we can actually transform the entire log-odds parameter table results into odds using the same <code>model_parameters()</code> function with the added input argument of “exponentiate”, like so:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Print parameters in odds </span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">model_parameters</span>(fit2, <span class="at">exponentiate =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span> <span class="fu">print_md</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Parameter</th>
<th style="text-align: center;">Odds Ratio</th>
<th style="text-align: center;">SE</th>
<th style="text-align: center;">95% CI</th>
<th style="text-align: center;">z</th>
<th style="text-align: center;">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: center;">0.39</td>
<td style="text-align: center;">0.04</td>
<td style="text-align: center;">(0.33, 0.47)</td>
<td style="text-align: center;">-9.79</td>
<td style="text-align: center;">&lt; .001</td>
</tr>
<tr class="even">
<td style="text-align: left;">fare</td>
<td style="text-align: center;">1.02</td>
<td style="text-align: center;">2.26e-03</td>
<td style="text-align: center;">(1.01, 1.02)</td>
<td style="text-align: center;">6.77</td>
<td style="text-align: center;">&lt; .001</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Knowing the significance values in odds, we can now say that the effect of <code>fare</code> in the increase of odds is statistically significant from <b>1</b>, <span class="math inline">\(p&lt;0.001\)</span> <a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a></p>
<p>A lot of fields, like medicine, prefer to output and report their logistic regression values in odds.</p>
</section>
<section id="predicted-probability" class="level3" data-number="5.2.3">
<h3 data-number="5.2.3" class="anchored" data-anchor-id="predicted-probability"><span class="header-section-number">5.2.3</span> Predicted Probability</h3>
<p>A convenient transformation is taking the log-odds and converting into probability. Then, our question becomes “Is there a relationship between the amount of fare and the probability of survival?”.</p>
<p>We can assess this relationship with the <code>predict_response()</code> function. It outputs a plot with the Y-axis as “the probability of <code>survival_b</code>” and the X-axis as the predictor (in this case <code>fare</code>) in raw units.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict_response</span>(fit2, <span class="at">terms =</span> <span class="st">"fare"</span>) <span class="sc">|&gt;</span> <span class="fu">plot</span>(<span class="at">show_data =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="binary-regression_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Again, the transformed outcome variable is the “probability of <code>survived_b</code>” (on the y-axis), so we can see that it is bounded between [0,100]. The logistic regression line also makes predictions between these bounds so we no longer have the model predicting unreasonable values/states. Lastly, we can now see how an increase in <code>fare</code> increases the probability of survival.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Critical Thinking">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Critical Thinking
</div>
</div>
<div class="callout-body-container callout-body">
<p>While the plot above looks very convincing that paying a <code>fare</code> over $400 seems to ensure 100% probability of survival, this model only has <i>one</i> predictor variable. There are a lot of other variables that are not accounted for. Certainly, we would need to consider other variables that may impact survival rates other than fare, and, at the very least, it would be quite surprising if only ’fare` ensured survival.</p>
</div>
</div>
</section>
</section>
<section id="two-continuous-predictors" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="two-continuous-predictors"><span class="header-section-number">5.3</span> Two Continuous Predictors</h2>
<p>“Is there a relationship between the amount of fare, age, and the log-odds/probability of survival?”</p>
<p>When we have two predictors, we are now conducting a multiple logistic regression. Recall that multiple regression, in general, allows us to control for the effects of multiple predictors on the outcome, and we are left with the unique effect of a predictor when controlling for other predictors.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>fit3 <span class="ot">&lt;-</span> <span class="fu">glm</span>(</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">formula =</span> survived_b <span class="sc">~</span> fare <span class="sc">+</span> age, </span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>), </span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> titanic2</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a><span class="do">## Print parameters in logit (i.e., log-odds) units</span></span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a><span class="fu">model_parameters</span>(fit3) <span class="sc">|&gt;</span> <span class="fu">print_md</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 17%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 29%">
<col style="width: 10%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Parameter</th>
<th style="text-align: center;">Log-Odds</th>
<th style="text-align: center;">SE</th>
<th style="text-align: center;">95% CI</th>
<th style="text-align: center;">z</th>
<th style="text-align: center;">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: center;">-0.51</td>
<td style="text-align: center;">0.17</td>
<td style="text-align: center;">(-0.84, -0.18)</td>
<td style="text-align: center;">-3.02</td>
<td style="text-align: center;">0.003</td>
</tr>
<tr class="even">
<td style="text-align: left;">fare</td>
<td style="text-align: center;">0.02</td>
<td style="text-align: center;">2.31e-03</td>
<td style="text-align: center;">(0.01, 0.02)</td>
<td style="text-align: center;">6.99</td>
<td style="text-align: center;">&lt; .001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">age</td>
<td style="text-align: center;">-0.02</td>
<td style="text-align: center;">5.24e-03</td>
<td style="text-align: center;">(-0.03, -5.32e-03)</td>
<td style="text-align: center;">-2.96</td>
<td style="text-align: center;">0.003</td>
</tr>
</tbody>
</table>
</div>
</div>
<section id="parameter-table-interpretation-log-odds-1" class="level3" data-number="5.3.1">
<h3 data-number="5.3.1" class="anchored" data-anchor-id="parameter-table-interpretation-log-odds-1"><span class="header-section-number">5.3.1</span> Parameter Table Interpretation (Log-odds)</h3>
<p>When the parameter table is in log-odds, we can now say the following:</p>
<blockquote class="blockquote">
<p>For every one unit increase in <code>fare</code>, there is a 0.02 increase in the log-odds of surviving when controlling for the effect of <code>age</code>. The unique (i.e., partial) effect of <code>fare</code> is significantly different from 0, <span class="math inline">\(p&lt;0.01\)</span>.</p>
</blockquote>
<blockquote class="blockquote">
<p>For every one unit increase in ‘age’, there is a 0.02 decrease in the log-odds of surviving when controlling for the effect of <code>fare</code>. The unique (i.e., partial) effect of <code>age</code> is significantly different from 0, <span class="math inline">\(p&lt;0.01\)</span>.</p>
</blockquote>
<p>Remember, in log-odds, if the value is positive, it is more likely for the event to occur, and if it is negative, it is more likely for the event to not occur.</p>
</section>
<section id="parameter-table-interpretation-odds-1" class="level3" data-number="5.3.2">
<h3 data-number="5.3.2" class="anchored" data-anchor-id="parameter-table-interpretation-odds-1"><span class="header-section-number">5.3.2</span> Parameter Table Interpretation (Odds)</h3>
<p>We can also present the results in odds.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Print parameters in odds </span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="fu">model_parameters</span>(fit3, <span class="at">exponentiate =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span> <span class="fu">print_md</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Parameter</th>
<th style="text-align: center;">Odds Ratio</th>
<th style="text-align: center;">SE</th>
<th style="text-align: center;">95% CI</th>
<th style="text-align: center;">z</th>
<th style="text-align: center;">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: center;">0.60</td>
<td style="text-align: center;">0.10</td>
<td style="text-align: center;">(0.43, 0.84)</td>
<td style="text-align: center;">-3.02</td>
<td style="text-align: center;">0.003</td>
</tr>
<tr class="even">
<td style="text-align: left;">fare</td>
<td style="text-align: center;">1.02</td>
<td style="text-align: center;">2.35e-03</td>
<td style="text-align: center;">(1.01, 1.02)</td>
<td style="text-align: center;">6.99</td>
<td style="text-align: center;">&lt; .001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">age</td>
<td style="text-align: center;">0.98</td>
<td style="text-align: center;">5.16e-03</td>
<td style="text-align: center;">(0.97, 0.99)</td>
<td style="text-align: center;">-2.96</td>
<td style="text-align: center;">0.003</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>When the parameter table is in odds, we can now say the following:</p>
<blockquote class="blockquote">
<p>For every one unit increase in <code>fare</code>, there is a 0.02 increase, or 2.0% increase, in the odds of surviving when controlling for the effect of <code>age</code>. The unique (i.e., partial) effect of <code>fare</code> is significantly different from 0, <span class="math inline">\(p&lt;0.01\)</span>.</p>
</blockquote>
<blockquote class="blockquote">
<p>For every one unit increase in ‘age’, there is a 0.02 decrease, or 2.0% decrease, in the odds of surviving when controlling for the effect of <code>fare</code>. The unique (i.e., partial) effect of <code>age</code> is significantly different from 0, <span class="math inline">\(p&lt;0.01\)</span>.</p>
</blockquote>
<p>Remember, in odds, if the value greater than 1, it is more likely for the event to occur, and if it less than 1, it is more likely for the event to not occur.</p>
</section>
<section id="predicted-probability-1" class="level3" data-number="5.3.3">
<h3 data-number="5.3.3" class="anchored" data-anchor-id="predicted-probability-1"><span class="header-section-number">5.3.3</span> Predicted Probability</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict_response</span>(fit3, <span class="at">terms =</span> <span class="st">"fare"</span>) <span class="sc">|&gt;</span> <span class="fu">plot</span>(<span class="at">show_data =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="binary-regression_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict_response</span>(fit3, <span class="at">terms =</span> <span class="st">"age"</span>) <span class="sc">|&gt;</span> <span class="fu">plot</span>(<span class="at">show_data =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="binary-regression_files/figure-html/unnamed-chunk-24-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The plots for predicted probabilities is helpful for highlighting the different effects for <code>fare</code> and <code>age</code>. As we see, there is a decrease in the probability of surviving as age increases, and there is an increase in the probability of surviving as the amount of fare increases.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Why not always use probability?">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Why not always use probability?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Although working with probabilities seems to be more easily understandable, we cannot have parameter estimates in probabilities. Therefore, results are often communicated in logits or odds since we can have estimates, uncertainty values (like standard deviations), and significance tests applied to them.</p>
</div>
</div>
</section>
</section>
<section id="one-dummy-coded-predictor" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="one-dummy-coded-predictor"><span class="header-section-number">5.4</span> One Dummy Coded Predictor</h2>
<p>Let’s consider the question “Is there a relationship between the type of <code>class</code> accommodation and the log-odds/probability of surviving”?</p>
<p>Remember, first we have to change our predictor variable to a factor (i.e., a dummy-coded variable), and then we can fit with <code>glm()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>titanic2<span class="sc">$</span>class <span class="ot">&lt;-</span> <span class="fu">factor</span>(titanic2<span class="sc">$</span>class, <span class="at">levels =</span><span class="fu">c</span>(<span class="st">"1st"</span>,<span class="st">"2nd"</span>,<span class="st">"3rd"</span>))</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>fit4 <span class="ot">&lt;-</span> <span class="fu">glm</span>(</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">formula =</span> survived_b <span class="sc">~</span> class, </span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>), </span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> titanic2</span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a><span class="fu">model_parameters</span>(fit4) <span class="sc">|&gt;</span> <span class="fu">print_md</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Parameter</th>
<th style="text-align: center;">Log-Odds</th>
<th style="text-align: center;">SE</th>
<th style="text-align: center;">95% CI</th>
<th style="text-align: center;">z</th>
<th style="text-align: center;">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: center;">0.53</td>
<td style="text-align: center;">0.14</td>
<td style="text-align: center;">(0.26, 0.81)</td>
<td style="text-align: center;">3.77</td>
<td style="text-align: center;">&lt; .001</td>
</tr>
<tr class="even">
<td style="text-align: left;">class (2nd)</td>
<td style="text-align: center;">-0.64</td>
<td style="text-align: center;">0.20</td>
<td style="text-align: center;">(-1.04, -0.24)</td>
<td style="text-align: center;">-3.13</td>
<td style="text-align: center;">0.002</td>
</tr>
<tr class="odd">
<td style="text-align: left;">class (3rd)</td>
<td style="text-align: center;">-1.66</td>
<td style="text-align: center;">0.18</td>
<td style="text-align: center;">(-2.01, -1.32)</td>
<td style="text-align: center;">-9.43</td>
<td style="text-align: center;">&lt; .001</td>
</tr>
</tbody>
</table>
</div>
</div>
<section id="parameter-table-interpretation-log-odds-2" class="level3" data-number="5.4.1">
<h3 data-number="5.4.1" class="anchored" data-anchor-id="parameter-table-interpretation-log-odds-2"><span class="header-section-number">5.4.1</span> Parameter Table Interpretation (Log-odds)</h3>
<p>Remember, although we are performing a logistic regression, it is still dummy-coded so our parameters estimates are given relative to the first category of the predictor variable. In this case, the “1st Class” is the reference group.</p>
<blockquote class="blockquote">
<p>The intercept is the average log-odds of surviving for the “1st Class” category. In this case, members of the “1st Class” have a 0.53 increase in the log-odds of surviving.</p>
</blockquote>
<blockquote class="blockquote">
<p>The members of the “2nd Class” have a 0.64 decrease in the log-odds of suriving relative to the “1st Class” (i.e., they have a worse chance of surviving).</p>
</blockquote>
<blockquote class="blockquote">
<p>The members of the “3rd Class” have 1.66 decrease in the log-odds of suriving relative to the “1st Class”.</p>
</blockquote>
<blockquote class="blockquote">
<p>There was a significant difference between the “1st Class” and 0, <span class="math inline">\(p&lt;0.01\)</span>. The difference between each class and the “1st Class” was significant, <span class="math inline">\(p&lt;0.01\)</span>.</p>
</blockquote>
</section>
<section id="estimating-means-and-plots" class="level3" data-number="5.4.2">
<h3 data-number="5.4.2" class="anchored" data-anchor-id="estimating-means-and-plots"><span class="header-section-number">5.4.2</span> Estimating means and plots</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>gmeans1 <span class="ot">&lt;-</span> <span class="fu">estimate_means</span>(fit4, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"class"</span>)) </span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>gmeans1 <span class="sc">|&gt;</span> <span class="fu">print_md</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Estimated Marginal Means</caption>
<thead>
<tr class="header">
<th style="text-align: left;">class</th>
<th style="text-align: right;">Probability</th>
<th style="text-align: left;">SE</th>
<th style="text-align: left;">95% CI</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1st</td>
<td style="text-align: right;">0.63</td>
<td style="text-align: left;">0.03</td>
<td style="text-align: left;">(0.56, 0.69)</td>
</tr>
<tr class="even">
<td style="text-align: left;">2nd</td>
<td style="text-align: right;">0.47</td>
<td style="text-align: left;">0.04</td>
<td style="text-align: left;">(0.40, 0.55)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3rd</td>
<td style="text-align: right;">0.24</td>
<td style="text-align: left;">0.02</td>
<td style="text-align: left;">(0.21, 0.28)</td>
</tr>
</tbody>
</table>
<p>Marginal means estimated at class</p>
</div>
</div>
</section>
<section id="parameter-table-interpretation-odds-2" class="level3" data-number="5.4.3">
<h3 data-number="5.4.3" class="anchored" data-anchor-id="parameter-table-interpretation-odds-2"><span class="header-section-number">5.4.3</span> Parameter Table Interpretation (Odds)</h3>
<p>Like in other logistic regression models, we can convert to odds ratios with <code>model_parameters</code> and “exponentiate” input argument.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">model_parameters</span>(fit4, <span class="at">exponentiate =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span> <span class="fu">print_md</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Parameter</th>
<th style="text-align: center;">Odds Ratio</th>
<th style="text-align: center;">SE</th>
<th style="text-align: center;">95% CI</th>
<th style="text-align: center;">z</th>
<th style="text-align: center;">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: center;">1.70</td>
<td style="text-align: center;">0.24</td>
<td style="text-align: center;">(1.29, 2.25)</td>
<td style="text-align: center;">3.77</td>
<td style="text-align: center;">&lt; .001</td>
</tr>
<tr class="even">
<td style="text-align: left;">class (2nd)</td>
<td style="text-align: center;">0.53</td>
<td style="text-align: center;">0.11</td>
<td style="text-align: center;">(0.35, 0.79)</td>
<td style="text-align: center;">-3.13</td>
<td style="text-align: center;">0.002</td>
</tr>
<tr class="odd">
<td style="text-align: left;">class (3rd)</td>
<td style="text-align: center;">0.19</td>
<td style="text-align: center;">0.03</td>
<td style="text-align: center;">(0.13, 0.27)</td>
<td style="text-align: center;">-9.43</td>
<td style="text-align: center;">&lt; .001</td>
</tr>
</tbody>
</table>
</div>
</div>
<blockquote class="blockquote">
<p>The intercept is the average odds of surviving for the “1st Class” category. In this case, members of the “1st Class” have a 0.70 increase, or 70% increase, in the odds of surviving.</p>
</blockquote>
<blockquote class="blockquote">
<p>The members of the “2nd Class” have a 0.47 decrease, or 47% decrease, in the odds of suriving relative to the “1st Class” (i.e., they have a worse chance of surviving). This is because 1 - 0.53 = 0.47.</p>
</blockquote>
<blockquote class="blockquote">
<p>The members of the “3rd Class” have 0.81 decrease, or 81% decrease, in the log-odds of suriving relative to the “1st Class” (i.e., they have a worse chance of surviving). Again, this is because 1 - 0.19 = 0.81.</p>
</blockquote>
<blockquote class="blockquote">
<p>There was a significant difference between the “1st Class” and 1, <span class="math inline">\(p&lt;0.01\)</span>. The difference between each class and the “1st Class” was significant, <span class="math inline">\(p&lt;0.01\)</span>.</p>
</blockquote>
</section>
<section id="predicted-probability-2" class="level3" data-number="5.4.4">
<h3 data-number="5.4.4" class="anchored" data-anchor-id="predicted-probability-2"><span class="header-section-number">5.4.4</span> Predicted Probability</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict_response</span>(fit4, <span class="at">terms =</span> <span class="st">"class"</span>) <span class="sc">|&gt;</span> <span class="fu">plot</span>(<span class="at">show_data =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="binary-regression_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>When the predicted probabilities are plotted, we can visualize the differences in probabilities of surviving between classes.</p>
</section>
</section>
<section id="one-dummy-coded-and-one-continuous-predictor" class="level2" data-number="5.5">
<h2 data-number="5.5" class="anchored" data-anchor-id="one-dummy-coded-and-one-continuous-predictor"><span class="header-section-number">5.5</span> One Dummy Coded and One Continuous Predictor</h2>
<p>“Is there a relationship between the amount of fare, class, and the log-odds/probability of survival?”</p>
<p>Again, multiple regression allows us to control for the effects of multiple predictors on the outcome, and we are left with the unique effect of a predictor when controlling for other predictors. In this case, the outcome variable will be <code>survived_b</code>, and the predictor variables will be <code>class</code> (categorical variable) and <code>age</code> (continuous variable).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>fit5 <span class="ot">&lt;-</span> <span class="fu">glm</span>(</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">formula =</span> survived_b <span class="sc">~</span> class <span class="sc">+</span> age, </span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>), </span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> titanic2</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a><span class="fu">model_parameters</span>(fit5) <span class="sc">|&gt;</span> <span class="fu">print_md</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Parameter</th>
<th style="text-align: center;">Log-Odds</th>
<th style="text-align: center;">SE</th>
<th style="text-align: center;">95% CI</th>
<th style="text-align: center;">z</th>
<th style="text-align: center;">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: center;">2.10</td>
<td style="text-align: center;">0.29</td>
<td style="text-align: center;">(1.54, 2.69)</td>
<td style="text-align: center;">7.17</td>
<td style="text-align: center;">&lt; .001</td>
</tr>
<tr class="even">
<td style="text-align: left;">class (2nd)</td>
<td style="text-align: center;">-1.04</td>
<td style="text-align: center;">0.22</td>
<td style="text-align: center;">(-1.48, -0.61)</td>
<td style="text-align: center;">-4.67</td>
<td style="text-align: center;">&lt; .001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">class (3rd)</td>
<td style="text-align: center;">-2.29</td>
<td style="text-align: center;">0.21</td>
<td style="text-align: center;">(-2.72, -1.88)</td>
<td style="text-align: center;">-10.73</td>
<td style="text-align: center;">&lt; .001</td>
</tr>
<tr class="even">
<td style="text-align: left;">age</td>
<td style="text-align: center;">-0.04</td>
<td style="text-align: center;">6.25e-03</td>
<td style="text-align: center;">(-0.05, -0.03)</td>
<td style="text-align: center;">-6.31</td>
<td style="text-align: center;">&lt; .001</td>
</tr>
</tbody>
</table>
</div>
</div>
<section id="paramter-table-interpretation-log-odds" class="level3" data-number="5.5.1">
<h3 data-number="5.5.1" class="anchored" data-anchor-id="paramter-table-interpretation-log-odds"><span class="header-section-number">5.5.1</span> Paramter Table Interpretation (Log-odds)</h3>
<blockquote class="blockquote">
<p>The intercept is the average log-odds of surviving for the “1st Class” category while accounting for the effect of <code>age</code>. In this case, members of the “1st Class” have a average log odds of 2.10 indiciating that passengers in the 1st Class are more likely to survive than not survive.</p>
</blockquote>
<blockquote class="blockquote">
<p>The members of the “2nd Class” have a 1.04 decrease in the log-odds of suriving relative to the “1st Class” while accounting for the effect of <code>age</code> (i.e., they have a worse chance of surviving).</p>
</blockquote>
<blockquote class="blockquote">
<p>The members of the “3rd Class” have 2.29 decrease in the log-odds of suriving relative to the “1st Class” while accounting for the effect of <code>age</code>. (i.e., they have a worse chance of surviving).</p>
</blockquote>
<blockquote class="blockquote">
<p>Because the intercept was significant, There was a significant difference between the “1st Class” and 0, <span class="math inline">\(p&lt;0.001\)</span>. Because each class was significant, The difference between each class and the “1st Class” was significant, <span class="math inline">\(p&lt;0.001\)</span>.</p>
</blockquote>
<blockquote class="blockquote">
<p>Lastly, while controlling for the effect of <code>class</code>, a one unit increase in age was significantly related to a 0.04 decrease in the log-odds of survival.</p>
</blockquote>
</section>
<section id="parameter-table-interpretation-odds-3" class="level3" data-number="5.5.2">
<h3 data-number="5.5.2" class="anchored" data-anchor-id="parameter-table-interpretation-odds-3"><span class="header-section-number">5.5.2</span> Parameter Table Interpretation (Odds)</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">model_parameters</span>(fit5, <span class="at">exponentiate =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span> <span class="fu">print_md</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Parameter</th>
<th style="text-align: center;">Odds Ratio</th>
<th style="text-align: center;">SE</th>
<th style="text-align: center;">95% CI</th>
<th style="text-align: center;">z</th>
<th style="text-align: center;">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: center;">8.16</td>
<td style="text-align: center;">2.39</td>
<td style="text-align: center;">(4.65, 14.66)</td>
<td style="text-align: center;">7.17</td>
<td style="text-align: center;">&lt; .001</td>
</tr>
<tr class="even">
<td style="text-align: left;">class (2nd)</td>
<td style="text-align: center;">0.35</td>
<td style="text-align: center;">0.08</td>
<td style="text-align: center;">(0.23, 0.55)</td>
<td style="text-align: center;">-4.67</td>
<td style="text-align: center;">&lt; .001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">class (3rd)</td>
<td style="text-align: center;">0.10</td>
<td style="text-align: center;">0.02</td>
<td style="text-align: center;">(0.07, 0.15)</td>
<td style="text-align: center;">-10.73</td>
<td style="text-align: center;">&lt; .001</td>
</tr>
<tr class="even">
<td style="text-align: left;">age</td>
<td style="text-align: center;">0.96</td>
<td style="text-align: center;">6.01e-03</td>
<td style="text-align: center;">(0.95, 0.97)</td>
<td style="text-align: center;">-6.31</td>
<td style="text-align: center;">&lt; .001</td>
</tr>
</tbody>
</table>
</div>
</div>
<blockquote class="blockquote">
<p>The intercept is the average odds of surviving for the “1st Class” category while accounting for the effect of <code>age</code>. In this case, members of the “1st Class” have a average odds of 8.16 indiciating that passengers in the 1st Class are more likely to survive.</p>
</blockquote>
<blockquote class="blockquote">
<p>The members of the “2nd Class” have a 0.35, or 35% decrease, in the odds of suriving relative to the “1st Class” while accounting for the effect of <code>age</code> (i.e., they have a worse chance of surviving).</p>
</blockquote>
<blockquote class="blockquote">
<p>The members of the “3rd Class” have 0.10 decrease, or 10% decrease, in the odds of suriving relative to the “1st Class” while accounting for the effect of <code>age</code>. (i.e., they have a worse chance of surviving).</p>
</blockquote>
<blockquote class="blockquote">
<p>There was a significant difference between the “1st Class” and 1, <span class="math inline">\(p&lt;0.01\)</span>. The difference between each class and the “1st Class” was significant, <span class="math inline">\(p&lt;0.01\)</span>.</p>
</blockquote>
<blockquote class="blockquote">
<p>Lastly, while accounting for the effect of <code>class</code>, a one unit increase in age was significantly related to a 0.04 decrease, or 4% decrease, in the odds of survival.</p>
</blockquote>
</section>
<section id="predicted-probabilities" class="level3" data-number="5.5.3">
<h3 data-number="5.5.3" class="anchored" data-anchor-id="predicted-probabilities"><span class="header-section-number">5.5.3</span> Predicted Probabilities</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict_response</span>(fit5, <span class="at">terms =</span> <span class="st">"age"</span>) <span class="sc">|&gt;</span> <span class="fu">plot</span>(<span class="at">show_data =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="binary-regression_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>With predicted probabilities, while accounting for <code>class</code>, we can see the probability of surviving is decreasing with age.</p>
</section>
<section id="estimating-means-and-plots-1" class="level3" data-number="5.5.4">
<h3 data-number="5.5.4" class="anchored" data-anchor-id="estimating-means-and-plots-1"><span class="header-section-number">5.5.4</span> Estimating Means and Plots</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>gmeans2 <span class="ot">&lt;-</span> <span class="fu">estimate_means</span>(fit5, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"class"</span>)) </span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>gmeans2 <span class="sc">|&gt;</span> <span class="fu">print_md</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Estimated Marginal Means</caption>
<thead>
<tr class="header">
<th style="text-align: left;">class</th>
<th style="text-align: right;">Probability</th>
<th style="text-align: left;">SE</th>
<th style="text-align: left;">95% CI</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1st</td>
<td style="text-align: right;">0.72</td>
<td style="text-align: left;">0.03</td>
<td style="text-align: left;">(0.65, 0.78)</td>
</tr>
<tr class="even">
<td style="text-align: left;">2nd</td>
<td style="text-align: right;">0.47</td>
<td style="text-align: left;">0.04</td>
<td style="text-align: left;">(0.40, 0.55)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3rd</td>
<td style="text-align: right;">0.21</td>
<td style="text-align: left;">0.02</td>
<td style="text-align: left;">(0.17, 0.24)</td>
</tr>
</tbody>
</table>
<p>Marginal means estimated at class</p>
</div>
</div>
</section>
</section>
</section>
<section id="assumptions" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Assumptions</h1>
<p>When we use logistic regression over regular linear regression, we benefit in terms of adhering to the assumptions of the linear model. We can see this benefit when we compare between the two models that have the same outcome and predictors.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">check_model</span>(fitlm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="binary-regression_files/figure-html/unnamed-chunk-33-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">check_model</span>(fit1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="binary-regression_files/figure-html/unnamed-chunk-33-2.png" class="img-fluid" width="672"></p>
</div>
</div>


</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p><code>check_residuals()</code> requires the package <code>qqplotr</code> to be installed.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>Recall that when odds <span class="math inline">\(=1\)</span>, that means both events are equally likely to happen. So when the odds read a value like <span class="math inline">\(1.02\)</span>, then we only consider the differences from 1 as meaningful. In this case, that increase is 0.02, or 2%, from our baseline value of 1.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>When the paramter table is in odds, the significance test is applied to see differences from an odds value of 1. This is because, again, an odds value of 1 means that an event occuring versus not occuring is equally likely.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./regression-review.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Regression Recap</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./linear-models.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Linear models</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">Introduction to Generalized Linear Modeling was written by Aaron Matthew Simmons and Jeffrey M. Girard.</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">This book was built with <a href="https://quarto.org/">Quarto</a>.</div>
  </div>
</footer>



</body></html>