<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Aaron Matthew Simmons and Jeffrey M. Girard">

<title>Introduction to Generalized Linear Modeling - 4&nbsp; count-regression</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./linear-models.html" rel="next">
<link href="./binary-regression.html" rel="prev">
<link href="./cover.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Introduction to Generalized Linear Modeling</span>
    </a>
  </div>
        <div class="quarto-navbar-tools ms-auto">
    <a href="https://www.github.com/affcomlab/learn-glms/" rel="" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
          <div id="quarto-search" class="" title="Search"></div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./count-regression.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">count-regression</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./regression-review.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Regression Recap</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./binary-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Binary Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./count-regression.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">count-regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./linear-models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Linear models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./summary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Summary</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Appendix</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#binomial-regression-with-bounded-counts" id="toc-binomial-regression-with-bounded-counts" class="nav-link active" data-scroll-target="#binomial-regression-with-bounded-counts"><span class="header-section-number">4.1</span> Binomial Regression with Bounded Counts</a></li>
  <li><a href="#data-demonstration" id="toc-data-demonstration" class="nav-link" data-scroll-target="#data-demonstration"><span class="header-section-number">4.2</span> Data Demonstration</a></li>
  <li><a href="#loading-the-packages-and-reading-in-data" id="toc-loading-the-packages-and-reading-in-data" class="nav-link" data-scroll-target="#loading-the-packages-and-reading-in-data"><span class="header-section-number">4.3</span> Loading the Packages and Reading in Data</a></li>
  <li><a href="#prepare-data-exploratory-data-analysis" id="toc-prepare-data-exploratory-data-analysis" class="nav-link" data-scroll-target="#prepare-data-exploratory-data-analysis"><span class="header-section-number">4.4</span> Prepare Data / Exploratory Data Analysis</a>
  <ul class="collapse">
  <li><a href="#plotting-relationships-to-dcl-9" id="toc-plotting-relationships-to-dcl-9" class="nav-link" data-scroll-target="#plotting-relationships-to-dcl-9"><span class="header-section-number">4.4.1</span> Plotting Relationships to DCL-9</a></li>
  </ul></li>
  <li><a href="#fitting-the-weighted-binomial-regression-models" id="toc-fitting-the-weighted-binomial-regression-models" class="nav-link" data-scroll-target="#fitting-the-weighted-binomial-regression-models"><span class="header-section-number">5</span> Fitting the Weighted Binomial Regression Models</a>
  <ul class="collapse">
  <li><a href="#one-continous-predictor" id="toc-one-continous-predictor" class="nav-link" data-scroll-target="#one-continous-predictor"><span class="header-section-number">5.1</span> One Continous Predictor</a>
  <ul class="collapse">
  <li><a href="#parameter-table-interpretation-log-odds" id="toc-parameter-table-interpretation-log-odds" class="nav-link" data-scroll-target="#parameter-table-interpretation-log-odds"><span class="header-section-number">5.1.1</span> Parameter Table Interpretation (Log-odds)</a></li>
  <li><a href="#parameter-table-interpretation-odds" id="toc-parameter-table-interpretation-odds" class="nav-link" data-scroll-target="#parameter-table-interpretation-odds"><span class="header-section-number">5.1.2</span> Parameter Table Interpretation (Odds)</a></li>
  <li><a href="#predicted-probability" id="toc-predicted-probability" class="nav-link" data-scroll-target="#predicted-probability"><span class="header-section-number">5.1.3</span> Predicted Probability</a></li>
  <li><a href="#parameter-table-interpretation-log-odds-1" id="toc-parameter-table-interpretation-log-odds-1" class="nav-link" data-scroll-target="#parameter-table-interpretation-log-odds-1"><span class="header-section-number">5.1.4</span> Parameter Table Interpretation (Log-odds)</a></li>
  <li><a href="#parameter-table-interpretation-odds-1" id="toc-parameter-table-interpretation-odds-1" class="nav-link" data-scroll-target="#parameter-table-interpretation-odds-1"><span class="header-section-number">5.1.5</span> Parameter Table Interpretation (Odds)</a></li>
  <li><a href="#predicted-probability-1" id="toc-predicted-probability-1" class="nav-link" data-scroll-target="#predicted-probability-1"><span class="header-section-number">5.1.6</span> Predicted Probability</a></li>
  </ul></li>
  <li><a href="#one-dummy-coded-predictor" id="toc-one-dummy-coded-predictor" class="nav-link" data-scroll-target="#one-dummy-coded-predictor"><span class="header-section-number">5.2</span> One Dummy Coded Predictor</a>
  <ul class="collapse">
  <li><a href="#parameter-table-interpretation-log-odds-2" id="toc-parameter-table-interpretation-log-odds-2" class="nav-link" data-scroll-target="#parameter-table-interpretation-log-odds-2"><span class="header-section-number">5.2.1</span> Parameter Table Interpretation (Log-odds)</a></li>
  <li><a href="#estimating-means-and-plots" id="toc-estimating-means-and-plots" class="nav-link" data-scroll-target="#estimating-means-and-plots"><span class="header-section-number">5.2.2</span> Estimating means and plots</a></li>
  <li><a href="#parameter-table-interpretation-odds-2" id="toc-parameter-table-interpretation-odds-2" class="nav-link" data-scroll-target="#parameter-table-interpretation-odds-2"><span class="header-section-number">5.2.3</span> Parameter Table Interpretation (Odds)</a></li>
  <li><a href="#predicted-probability-2" id="toc-predicted-probability-2" class="nav-link" data-scroll-target="#predicted-probability-2"><span class="header-section-number">5.2.4</span> Predicted Probability</a></li>
  </ul></li>
  <li><a href="#one-dummy-coded-predictor-and-one-continous-predictor" id="toc-one-dummy-coded-predictor-and-one-continous-predictor" class="nav-link" data-scroll-target="#one-dummy-coded-predictor-and-one-continous-predictor"><span class="header-section-number">5.3</span> One Dummy Coded Predictor and One Continous Predictor</a>
  <ul class="collapse">
  <li><a href="#paramter-table-interpretation-log-odds" id="toc-paramter-table-interpretation-log-odds" class="nav-link" data-scroll-target="#paramter-table-interpretation-log-odds"><span class="header-section-number">5.3.1</span> Paramter Table Interpretation (Log-odds)</a></li>
  <li><a href="#parameter-table-interpretation-odds-ratio" id="toc-parameter-table-interpretation-odds-ratio" class="nav-link" data-scroll-target="#parameter-table-interpretation-odds-ratio"><span class="header-section-number">5.3.2</span> Parameter Table Interpretation (Odds Ratio)</a></li>
  </ul></li>
  </ul></li>
  </ul>
<div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://www.github.com/affcomlab/learn-glms/issues/new" class="toc-action">Report an issue</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">count-regression</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="binomial-regression-with-bounded-counts" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="binomial-regression-with-bounded-counts"><span class="header-section-number">4.1</span> Binomial Regression with Bounded Counts</h2>
<p>When your outcome variable is a <i>bounded count variable</i>, it has a lower bound of 0 and a fixed upper bound. Specifically, each value of this variable represents the proportion of a success, or presence/endorsement, of that value; in other words, each value in that outcome variable can be thought of as a binary proportion. We can use what’s called a <i>weighted binomial regression</i> to model this bounded count variable.</p>
<p>A bounded count variable is easiest to understand and identify with an example. Imagine a test that is made up of 10 questions. To obtain a score on this test, you count how many questions were answered correct out of the 10 questions. In this case, each specific question is made up of a binary event (correct or incorrect). So, the minimum score on this test is 0, and the maximum score on this test is 10. And when we have many people take this test, we get a distribution of scores that can represent the probability/proportion correct of this outcome variable.</p>
<p>Therefore, when we can represent the probability/proportion correct of a fixed upper bound of an outcome variable, based on the success/failure or presence/absence of each value in that outcome variable, we can update binary regression very easily as a <i>weighted binomial regression</i>.</p>
<p>Also, in this treatment of the data, the items are <b>interchangeable</b> in terms of their order. So like in our example of a test that is made up of 10 questions, if the final score for one test-taker is a 5/10, we do not care which 5 questions were correct – this person’s score is treated as any 5 questions correct out of 10. This plays a role in how we interpret the model results later.</p>
</section>
<section id="data-demonstration" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="data-demonstration"><span class="header-section-number">4.2</span> Data Demonstration</h2>
<p><span style="background-color: #FFFF00"> The data for this weighted binomial regression section features a bounded count variable in the form of a score on the Patient Health Questionnaire (PHQ-9). The score on this self-report questionnaire involves adding up the total number of points assigned to each of 9 questions (where each question is worth 3 points); therefore, the minimum score for any patient is 0, and the maximum score is 27 points. According to the PHQ-9, the higher the score, the more severe depression a patient has.</span></p>
<p>Notice that when talking about the score for any patient who takes this questionnaire, we are only concerned with the final score out of 27 points, and we do not make a big deal about any one question on the exam, or the order of the questions. So, we are treating the items on this questionnaire as interchangeable.</p>
<p>The question we will ask and answer with weighted binomial regression is what can predict a high PHQ-9 score. First, we will consider as our main predictor variable the <code>income_ratio</code> variable where the higher the amount of this ratio, the more income one has relative to debt.</p>
<ul>
<li><p>Data: <a href="./depression.csv" download=""> depression.csv </a> </p></li>
<li><p>Data: <a href="./depression_checklist.csv" download=""> depression_checklist.csv </a></p></li>
</ul>
</section>
<section id="loading-the-packages-and-reading-in-data" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="loading-the-packages-and-reading-in-data"><span class="header-section-number">4.3</span> Loading the Packages and Reading in Data</h2>
<p>In addition to our usual packages (<code>tidyverse</code>, <code>easystats</code>, and <code>ggeffects</code>), we will also need to load <code>DHARMa</code> and <code>qqplotr</code> in order to make our plots for our weighted binary regression models.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Load packages</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(easystats)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggeffects)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(DHARMa)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(qqplotr)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="do">## Read in data from file</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>depression <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"depression_checklist.csv"</span>)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>depression</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 297 × 13
   gender children finances support dcl_1 dcl_2 dcl_3 dcl_4 dcl_5 dcl_6 dcl_7
    &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
 1      0        0        0   2.54      1     1     1     1     1     1     1
 2      1        1        1   3.92      1     1     1     1     1     1     1
 3      1        0        2   4         0     0     0     0     0     0     0
 4      0        0        1   1.42      1     1     1     1     0     1     0
 5      1        1        1   0.958     1     1     1     1     1     1     1
 6      0        0        2   2.92      0     0     0     0     0     0     0
 7      0        1        1   3.21      1     1     1     1     1     1     1
 8      1        1        1   2.33      0     0     0     0     0     0     0
 9      1        1        2   2.42      0     0     1     1     1     0     0
10      0        0        1   2.33      1     1     1     1     1     1     1
# ℹ 287 more rows
# ℹ 2 more variables: dcl_8 &lt;dbl&gt;, dcl_9 &lt;dbl&gt;</code></pre>
</div>
</div>
<p>This data shows records for 297 patients screened with the DCL-9 where each row is one participant.</p>
<p>Here’s a table of our variables in this dataset:</p>
<table class="table">
<colgroup>
<col style="width: 18%">
<col style="width: 46%">
<col style="width: 16%">
<col style="width: 18%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th style="text-align: left;">Description</th>
<th style="text-align: right;">Values</th>
<th style="text-align: center;">Measurement</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>gender</code></td>
<td style="text-align: left;">Gender of Participant (0 = Female, 1 = Male)</td>
<td style="text-align: right;">Integer</td>
<td style="text-align: center;">Ordinal</td>
</tr>
<tr class="even">
<td><code>children</code></td>
<td style="text-align: left;">Has Children (0 = no, 1 = yes)</td>
<td style="text-align: right;">Integer</td>
<td style="text-align: center;">Nominal</td>
</tr>
<tr class="odd">
<td><code>finances</code></td>
<td style="text-align: left;">Amount of Money Per Month (0 = not enough, 1 = just enough, 2 = some extra)</td>
<td style="text-align: right;">Integer</td>
<td style="text-align: center;">Ordinal</td>
</tr>
<tr class="even">
<td><code>support</code></td>
<td style="text-align: left;">Amount of Social Support</td>
<td style="text-align: right;">Double</td>
<td style="text-align: center;">Scale</td>
</tr>
<tr class="odd">
<td><code>dcl1</code> to <code>dcl9</code></td>
<td style="text-align: left;">Depression Symptoms (0 = absent, 1 = present)</td>
<td style="text-align: right;">Integer</td>
<td style="text-align: center;">Ordinal</td>
</tr>
</tbody>
</table>
</section>
<section id="prepare-data-exploratory-data-analysis" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="prepare-data-exploratory-data-analysis"><span class="header-section-number">4.4</span> Prepare Data / Exploratory Data Analysis</h2>
<p>For weighted binomial regression, in order to model the DCL-9 score as the outcome variable, we need to re-code each DCL score for each participant as a weighted proportion out of the max score of 9. Here, we will use the <code>mutate()</code> function from the <code>dplyr</code> package (which is a package that automatically loaded with <code>tidyverse</code>) to add a three new columns to our data: the first will be <code>dcl_max</code> which is the max score (9) any one participant can have on the DCL-9, the second is <code>dcl_sum</code> which is the total sum score across all DCL-9 questions, and the third column is <code>dcl9_p</code>, which is hte weighted proportion, or fraction, for a participant out of max score of 9.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># depression2 &lt;- </span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="co">#   depression |&gt; </span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="co">#   mutate(</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="co">#     phq9_max = 27, # maximum possible score (can be same or different per row)</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="co">#     phq9_p = phq9 / phq9_max # proportion of maximum possible score per row</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="co">#   ) </span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>depression2 <span class="ot">&lt;-</span> </span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>  depression <span class="sc">|&gt;</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">dcl_max =</span> <span class="dv">9</span>, </span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">dcl_sum =</span> <span class="fu">rowSums</span>(<span class="fu">pick</span>(dcl_1<span class="sc">:</span>dcl_9)),</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">dcl9_p =</span> dcl_sum <span class="sc">/</span> dcl_max</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>depression2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 297 × 16
   gender children finances support dcl_1 dcl_2 dcl_3 dcl_4 dcl_5 dcl_6 dcl_7
    &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
 1      0        0        0   2.54      1     1     1     1     1     1     1
 2      1        1        1   3.92      1     1     1     1     1     1     1
 3      1        0        2   4         0     0     0     0     0     0     0
 4      0        0        1   1.42      1     1     1     1     0     1     0
 5      1        1        1   0.958     1     1     1     1     1     1     1
 6      0        0        2   2.92      0     0     0     0     0     0     0
 7      0        1        1   3.21      1     1     1     1     1     1     1
 8      1        1        1   2.33      0     0     0     0     0     0     0
 9      1        1        2   2.42      0     0     1     1     1     0     0
10      0        0        1   2.33      1     1     1     1     1     1     1
# ℹ 287 more rows
# ℹ 5 more variables: dcl_8 &lt;dbl&gt;, dcl_9 &lt;dbl&gt;, dcl_max &lt;dbl&gt;, dcl_sum &lt;dbl&gt;,
#   dcl9_p &lt;dbl&gt;</code></pre>
</div>
</div>
<section id="plotting-relationships-to-dcl-9" class="level3" data-number="4.4.1">
<h3 data-number="4.4.1" class="anchored" data-anchor-id="plotting-relationships-to-dcl-9"><span class="header-section-number">4.4.1</span> Plotting Relationships to DCL-9</h3>
<p>Let’s first plot to see any relationship between the <code>support</code> and the weighted DCL-9 score (<code>dcl9_p</code>). We tend to see that more of the data points, especially at higher DCL-9 scores, fall in the higher values of <code>support</code> which suggests a positive relationship between support and depression severity; in other words, the higher the support, the higher the score on the DCL-9 (and more depression symptoms). While this may seem visually counter-intuitive, note that it is possible that most people in our sample may have depression symptoms despite having support, and that the plot is misleading (especially since the amount of <code>dcl9_p</code> scores are visually about the same across the higher levels of <code>support</code>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(depression2, <span class="fu">aes</span>(<span class="at">x =</span> support, <span class="at">y =</span> dcl9_p)) <span class="sc">+</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> mytheme</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="count-regression_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="fitting-the-weighted-binomial-regression-models" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Fitting the Weighted Binomial Regression Models</h1>
<section id="one-continous-predictor" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="one-continous-predictor"><span class="header-section-number">5.1</span> One Continous Predictor</h2>
<p>When we fit our weighted binomial regression, we now will use the <code>glm()</code> function.</p>
<p>We did a lot of work already with the <code>lm()</code> in the “Regression Recap”. The <code>glm()</code> function is in many ways the same as the <code>lm()</code> function. Even the syntax for how we write the equation is the same. In addition, we can use the same <code>model_parameters()</code> function to get our table of parameter estimates. Indeed, we will use the <code>glm()</code> function for the remainder of the rest of the online modules.</p>
<p>But for weighted binomial regression, notice that the <code>glm()</code> function has two more input arguments. These input arguments are the “family” input argument, which requires which “family of distributions” to use and which “link function” choice, and a “weights” argument, which is a column in the dataset that represents the max score for each proportion.</p>
<p>For weighted binary regression, we supply the <b>binomial</b> distribution and the <b>logit</b> link function into the “family” input argument, and <code>dcl9_max</code> column name for the “weights” input argument.</p>
<p>As mentioned before, we will consider the effect of <code>support</code>.</p>
<p>We then assess the results with <code>model_paramters()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>fit2 <span class="ot">&lt;-</span> <span class="fu">glm</span>(</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">formula =</span> dcl9_p <span class="sc">~</span> support,</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>),</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">weights =</span> dcl_max,</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> depression2</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a><span class="fu">model_parameters</span>(fit2) <span class="sc">|&gt;</span> <span class="fu">print_md</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Parameter</th>
<th style="text-align: center;">Log-Odds</th>
<th style="text-align: center;">SE</th>
<th style="text-align: center;">95% CI</th>
<th style="text-align: center;">z</th>
<th style="text-align: center;">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: center;">1.75</td>
<td style="text-align: center;">0.13</td>
<td style="text-align: center;">(1.50, 2.01)</td>
<td style="text-align: center;">13.43</td>
<td style="text-align: center;">&lt; .001</td>
</tr>
<tr class="even">
<td style="text-align: left;">support</td>
<td style="text-align: center;">-0.52</td>
<td style="text-align: center;">0.05</td>
<td style="text-align: center;">(-0.61, -0.42)</td>
<td style="text-align: center;">-10.81</td>
<td style="text-align: center;">&lt; .001</td>
</tr>
</tbody>
</table>
</div>
</div>
<section id="parameter-table-interpretation-log-odds" class="level3" data-number="5.1.1">
<h3 data-number="5.1.1" class="anchored" data-anchor-id="parameter-table-interpretation-log-odds"><span class="header-section-number">5.1.1</span> Parameter Table Interpretation (Log-odds)</h3>
<p>Again, the parameter table output from a model fit with <code>glm()</code> looks very similar to parameter table outputs from models fit with <code>lm()</code>. But there is a <b>big</b> difference – in <code>glm()</code> models, we are no longer working in the same raw units!</p>
<p>This difference is clear in the second column of the output table: “Log-Odds”. Because we fit a logistic regression with a logit function, the parameter values are in “log-odds” unit. Technically, when <code>support</code> is in log-odds units, we can only say:</p>
<blockquote class="blockquote">
<p>For every one 1 unit increase in <code>support</code>, there is a 0.52 decrease in the log-odds of having a one-unit higher DCL-9 score.</p>
</blockquote>
<p>Although this is technically true, it isn’t at first clear what it means to have a “0.52 unit decrease in log-odds of <code>dcl9_p</code>”. Let’s interpret the <span class="math inline">\(-0.52\)</span> log-odds value:</p>
<ul>
<li><p>If log-odds $ = -0.52$, then it is less than 0, meaning it is more likely to have a lower DCL-9 score (than a higher DCL-9 score) when we use <code>support</code> as a predictor.</p></li>
<li><p>This effect is also statistically significant from 0 (<span class="math inline">\(p&lt;0.001\)</span>). Remember, with log-odds, a value of 0 means it is equally likely for an event to occur or not occur. In this case, since it is significantly less than 0, we can say it is more likely to not have a symptom than have a symptom (i.e.&nbsp;score less on the DCL-9 than score more) when predicted by <code>support</code>.</p></li>
<li><p>As mentioned before, with weighted binomial regression the values of the outcome variable are interchangeable, so our parameter results speak in reference to obtaining <i>one</i> value difference on the outcome variable. Therefore, when log-odds <span class="math inline">\(= -0.52\)</span>, that is in reference to decreasing (because it is negative) the outcome variable score by one value lower.</p></li>
</ul>
</section>
<section id="parameter-table-interpretation-odds" class="level3" data-number="5.1.2">
<h3 data-number="5.1.2" class="anchored" data-anchor-id="parameter-table-interpretation-odds"><span class="header-section-number">5.1.2</span> Parameter Table Interpretation (Odds)</h3>
<p>We can also present the results in odds ratios by using the “exponentiate” input argument.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">model_parameters</span>(fit2, <span class="at">exponentiate =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span> <span class="fu">print_md</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Parameter</th>
<th style="text-align: center;">Odds Ratio</th>
<th style="text-align: center;">SE</th>
<th style="text-align: center;">95% CI</th>
<th style="text-align: center;">z</th>
<th style="text-align: center;">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: center;">5.77</td>
<td style="text-align: center;">0.75</td>
<td style="text-align: center;">(4.48, 7.48)</td>
<td style="text-align: center;">13.43</td>
<td style="text-align: center;">&lt; .001</td>
</tr>
<tr class="even">
<td style="text-align: left;">support</td>
<td style="text-align: center;">0.60</td>
<td style="text-align: center;">0.03</td>
<td style="text-align: center;">(0.54, 0.65)</td>
<td style="text-align: center;">-10.81</td>
<td style="text-align: center;">&lt; .001</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Now that we are in odds, we can adjust our previous interpretation of the <code>support</code> parameter for odds:</p>
<blockquote class="blockquote">
<p>For every one unit increase in <code>support</code>, there is a 0.40 decrease, or a 40% decrease, in the odds of having a one-unit higher DCL-9 score.</p>
</blockquote>
<p>Recall that when odds <span class="math inline">\(=1\)</span>, that means both events are equally likely to happen. So for example, here we read an odds value of <span class="math inline">\(0.60\)</span>, then we only consider the differences from 1 as meaningful. In this case, that is a decrease of 0.40, or 40%, from our baseline value of 1.</p>
<p>Also from the output table, we know the significance values in odds and we can now say that the effect of <code>support</code> in the decrease of odds is statistically significant from <b>1</b>, <span class="math inline">\(p&lt;0.001\)</span> <a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
<p>A lot of fields, like medicine, prefer to output and report their logistic regression values in odds.</p>
</section>
<section id="predicted-probability" class="level3" data-number="5.1.3">
<h3 data-number="5.1.3" class="anchored" data-anchor-id="predicted-probability"><span class="header-section-number">5.1.3</span> Predicted Probability</h3>
<p>A convenient transformation is taking the log-odds and converting into probability. Then, our question becomes “Is there a relationship between support and the probability of scoring one value different on the DCL-9?”.</p>
<p>We can assess this relationship with the <code>predict_response()</code> function. It outputs a plot with the Y-axis as “the probability of <code>DCL-9</code>” and the X-axis as the predictor (in this case <code>support</code>) in raw units, and it overlays the predicted probability on top of the data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict_response</span>(fit2, <span class="at">terms =</span> <span class="st">"support"</span>) <span class="sc">|&gt;</span> <span class="fu">plot</span>(<span class="at">show_data =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="count-regression_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Again, the transformed outcome variable is the “probability of <code>dcl9_p</code>” (on the y-axis), so we can see that it is bounded between [0,100]. The logistic regression line also makes predictions between these bounds so we no longer have the model predicting unreasonable values/states which would happen if we didn’t consider using the <code>glm()</code> function. Lastly, we can now see how an increase in <code>suppport</code> leads to a decrease in the probability of scoring one score lower on the DCL-9.</p>
<p>Also notice that our prediction line is more in agreement with the general intuition that the higher support one has, the less depression symptoms one may have. This is more clear now that the model can pick apart this relationship that would be hard to see if we only relied on a solely visual inspection.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Why not always use probability?">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Why not always use probability?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Although working with probabilities seems to be more easily understandable, we cannot have parameter estimates in probabilities. Therefore, results are often communicated in logits or odds since we can have estimates, uncertainty values (like standard deviations), and significance tests applied to them.</p>
</div>
</div>
<p><span style="background-color: #FFFF00"> ## Two Continous Predictors</span></p>
<p>“Is there a relationship between the support, age, and the score on the PHQ-9?”</p>
<p>When we have two predictors, we are now conducting a multiple weighted binomial (logistic) regression. Recall that multiple regression, in general, allows us to control for the effects of multiple predictors on the outcome, and we are left with the unique effect of a predictor when controlling for other predictors.</p>
<p>Once again, let’s fit this model with the <code>glm()</code> function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># fit3 &lt;- glm(</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="co">#   formula = phq9_p ~ income_ratio + age, </span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="co">#   family = binomial(link = "logit"),</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="co">#   weights = phq9_max,</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="co">#   data = depression2</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="co"># )</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a><span class="co"># </span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a><span class="co"># ## Print parameters in logit (i.e., log-odds) units</span></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a><span class="co"># model_parameters(fit3) |&gt; print_md()</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="parameter-table-interpretation-log-odds-1" class="level3" data-number="5.1.4">
<h3 data-number="5.1.4" class="anchored" data-anchor-id="parameter-table-interpretation-log-odds-1"><span class="header-section-number">5.1.4</span> Parameter Table Interpretation (Log-odds)</h3>
<p>When the parameter table is in log-odds, we can now say the following:</p>
<blockquote class="blockquote">
<p>For every one unit increase in <code>income_ratio</code>, there is a 0.16 decrease in the log-odds of having a one-unit higher PHQ-9 score (and greater chance of having severe depression) while controlling for the effect of <code>age</code>. The unique (i.e., partial) effect of <code>income_ratio</code> is significantly different from 0, <span class="math inline">\(p&lt;0.001\)</span>.</p>
</blockquote>
<blockquote class="blockquote">
<p>For every one unit increase in <code>age</code>, there is a 6.95e^-3 increase (because it is positive) in the log-odds of having a one-unit higher PHQ-9 score (and a greater chacne of having severe depression) when controlling for the effect of <code>income_ratio</code>. The unique (i.e., partial) effect of <code>age</code> is significantly different from 0, <span class="math inline">\(p&lt;0.01\)</span>.</p>
</blockquote>
<p>Remember, in log-odds, if the value is positive, it is more likely for the event to occur, and if it is negative, it is more likely for the event to not occur.</p>
</section>
<section id="parameter-table-interpretation-odds-1" class="level3" data-number="5.1.5">
<h3 data-number="5.1.5" class="anchored" data-anchor-id="parameter-table-interpretation-odds-1"><span class="header-section-number">5.1.5</span> Parameter Table Interpretation (Odds)</h3>
<p>We can also present the results in odds.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Print parameters in odds </span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="co"># model_parameters(fit3, exponentiate = TRUE) |&gt; print_md()</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>When the parameter table is in odds, we can now say the following:</p>
<blockquote class="blockquote">
<p>For every one unit increase in <code>income_ratio</code>, there is a 0.15 decrease, or 15.0% decrease, in the odds ratio of having a one-unit higher PHQ-9 score when controlling for the effect of <code>age</code>. The unique (i.e., partial) effect of <code>fare</code> is significantly different from 0, <span class="math inline">\(p&lt;0.01\)</span>.</p>
</blockquote>
<blockquote class="blockquote">
<p>For every one unit increase in <code>age</code>, there is a 0.01 increase, or 1.0% increase, in the odds ratio of having a one-unit higher PHQ-9 score when controlling for the effect of <code>income_ratio</code>. The unique (i.e., partial) effect of <code>age</code> is significantly different from 0, <span class="math inline">\(p&lt;0.001\)</span>.</p>
</blockquote>
<p>Remember, in odds, if the value greater than 1, it is more likely for the event to occur, and if it less than 1, it is more likely for the event to not occur.</p>
<p>At this point, it is interesting to consider that the higher the <code>income_ratio</code> amount, then the lower the chance of a one-unit increase of scores on the PHQ-9, whereas the higher the <code>age</code>, then the higher the chance of a one-unit increase on the PHQ-9</p>
</section>
<section id="predicted-probability-1" class="level3" data-number="5.1.6">
<h3 data-number="5.1.6" class="anchored" data-anchor-id="predicted-probability-1"><span class="header-section-number">5.1.6</span> Predicted Probability</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># predict_response(fit3, terms = "income_ratio") |&gt; plot(show_data = TRUE)</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="co"># predict_response(fit3, terms = "age") |&gt; plot(show_data = TRUE)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The plots for predicted probabilities is helpful for highlighting the different effects for <code>income_ratio</code> and <code>age</code> on the probability of obtaining a one-unit higher score on the PHQ-9. As we see, there is a decrease in the probability of a higher score as <code>income_ratio</code> increases, and there is an increase in the probability of surviving as <code>age</code> increases.</p>
<p></p>
</section>
</section>
<section id="one-dummy-coded-predictor" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="one-dummy-coded-predictor"><span class="header-section-number">5.2</span> One Dummy Coded Predictor</h2>
<p>Let’s consider the question “Is there a relationship between gender and the log-odds/probability of scoring one-unit higher on the DCL-9?”</p>
<p>Remember, first we have to change our predictor variable to a factor (i.e., a dummy-coded variable), and then we can fit with <code>glm()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>depression2<span class="sc">$</span>gender <span class="ot">&lt;-</span> <span class="fu">factor</span>(depression2<span class="sc">$</span>gender, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Female"</span>,<span class="st">"Male"</span>)) <span class="co">#change to factor</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>fit4 <span class="ot">&lt;-</span> <span class="fu">glm</span>(</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">formula =</span> dcl9_p <span class="sc">~</span> gender, </span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>), </span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">weights =</span> dcl_max,</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> depression2</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a><span class="fu">model_parameters</span>(fit4) <span class="sc">|&gt;</span> <span class="fu">print_md</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Parameter</th>
<th style="text-align: center;">Log-Odds</th>
<th style="text-align: center;">SE</th>
<th style="text-align: center;">95% CI</th>
<th style="text-align: center;">z</th>
<th style="text-align: center;">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: center;">0.29</td>
<td style="text-align: center;">0.06</td>
<td style="text-align: center;">(0.17, 0.42)</td>
<td style="text-align: center;">4.57</td>
<td style="text-align: center;">&lt; .001</td>
</tr>
<tr class="even">
<td style="text-align: left;">gender (Male)</td>
<td style="text-align: center;">0.24</td>
<td style="text-align: center;">0.08</td>
<td style="text-align: center;">(0.08, 0.40)</td>
<td style="text-align: center;">2.89</td>
<td style="text-align: center;">0.004</td>
</tr>
</tbody>
</table>
</div>
</div>
<section id="parameter-table-interpretation-log-odds-2" class="level3" data-number="5.2.1">
<h3 data-number="5.2.1" class="anchored" data-anchor-id="parameter-table-interpretation-log-odds-2"><span class="header-section-number">5.2.1</span> Parameter Table Interpretation (Log-odds)</h3>
<p>Remember, although we are performing a weighted binomial (logistic) regression, it is still dummy-coded so our parameters estimates are given relative to the first category of the predictor variable. In this case, the females are the reference group.</p>
<blockquote class="blockquote">
<p>The intercept is the average log-odds of scoring one unit higher on the DCL-9 for females. In this case, females have a 0.29 log-odds of scoring one unit higher on the DCL-9, which means it is more likely for them to score one unit higher on the DCL-9 (since it is a log odds greater than 0)</p>
</blockquote>
<blockquote class="blockquote">
<p>Men have a 0.24 increase in the log-odds of scoring one unit higher on the PHQ-9 relative to women (i.e., they have greater chance of scoring higher).</p>
</blockquote>
<blockquote class="blockquote">
<p>There was a significant difference in the log-odds women from 0, <span class="math inline">\(p&lt;0.001\)</span>. The difference between women and men was significant, <span class="math inline">\(p&lt;0.01\)</span>.</p>
</blockquote>
</section>
<section id="estimating-means-and-plots" class="level3" data-number="5.2.2">
<h3 data-number="5.2.2" class="anchored" data-anchor-id="estimating-means-and-plots"><span class="header-section-number">5.2.2</span> Estimating means and plots</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>gmeans1 <span class="ot">&lt;-</span> <span class="fu">estimate_means</span>(fit4, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"gender"</span>)) </span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>gmeans1 <span class="sc">|&gt;</span> <span class="fu">print_md</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Estimated Marginal Means</caption>
<thead>
<tr class="header">
<th style="text-align: left;">gender</th>
<th style="text-align: right;">Probability</th>
<th style="text-align: left;">SE</th>
<th style="text-align: left;">95% CI</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Female</td>
<td style="text-align: right;">0.57</td>
<td style="text-align: left;">0.02</td>
<td style="text-align: left;">(0.54, 0.60)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Male</td>
<td style="text-align: right;">0.63</td>
<td style="text-align: left;">0.01</td>
<td style="text-align: left;">(0.61, 0.65)</td>
</tr>
</tbody>
</table>
<p>Marginal means estimated at gender</p>
</div>
</div>
</section>
<section id="parameter-table-interpretation-odds-2" class="level3" data-number="5.2.3">
<h3 data-number="5.2.3" class="anchored" data-anchor-id="parameter-table-interpretation-odds-2"><span class="header-section-number">5.2.3</span> Parameter Table Interpretation (Odds)</h3>
<p>Like in other logistic regression models, we can convert to odds ratios with <code>model_parameters</code> and “exponentiate” input argument.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">model_parameters</span>(fit4, <span class="at">exponentiate =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span> <span class="fu">print_md</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Parameter</th>
<th style="text-align: center;">Odds Ratio</th>
<th style="text-align: center;">SE</th>
<th style="text-align: center;">95% CI</th>
<th style="text-align: center;">z</th>
<th style="text-align: center;">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: center;">1.34</td>
<td style="text-align: center;">0.09</td>
<td style="text-align: center;">(1.18, 1.52)</td>
<td style="text-align: center;">4.57</td>
<td style="text-align: center;">&lt; .001</td>
</tr>
<tr class="even">
<td style="text-align: left;">gender (Male)</td>
<td style="text-align: center;">1.27</td>
<td style="text-align: center;">0.10</td>
<td style="text-align: center;">(1.08, 1.49)</td>
<td style="text-align: center;">2.89</td>
<td style="text-align: center;">0.004</td>
</tr>
</tbody>
</table>
</div>
</div>
<blockquote class="blockquote">
<p>The intercept is the average odds of scoring one-unit higher on the PHQ-9 for women. In this case, women have a base odds of 1.32 for scoring higher on the DCL-9. Since it is greater than 1, it is more likely for someone to score one-unit higher.</p>
</blockquote>
<blockquote class="blockquote">
<p>Men have a 0.27 increase, or 27% increase, in the odds of scoring one-unit higher on the PHQ-9 relative to women (i.e., they have a greater chance at scoring higher on DCL-9). This is because 1.27 - 1 = 0.27.</p>
</blockquote>
<blockquote class="blockquote">
<p>There was a significant difference for women in the odds ratio from 1, <span class="math inline">\(p&lt;0.001\)</span>. The difference between women and men was also significant, <span class="math inline">\(p&lt;0.01\)</span>.</p>
</blockquote>
<p>In other words, both log-odds and odds ratio show that men have a increased chance of scoring one-unit higher on the DCL-9 relative to women meaning they are more likely to score for more depression symptoms than women.</p>
</section>
<section id="predicted-probability-2" class="level3" data-number="5.2.4">
<h3 data-number="5.2.4" class="anchored" data-anchor-id="predicted-probability-2"><span class="header-section-number">5.2.4</span> Predicted Probability</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict_response</span>(fit4, <span class="at">terms =</span> <span class="st">"gender"</span>) <span class="sc">|&gt;</span> <span class="fu">plot</span>(<span class="at">show_data =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="count-regression_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>When the predicted probabilities are plotted, we can visualize the differences in probabilities of women versus men.</p>
</section>
</section>
<section id="one-dummy-coded-predictor-and-one-continous-predictor" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="one-dummy-coded-predictor-and-one-continous-predictor"><span class="header-section-number">5.3</span> One Dummy Coded Predictor and One Continous Predictor</h2>
<p>“Is there a relationship between the income ratio, gender, and the log-odds/probability of scoring one-unit higher on the PHQ-9?”</p>
<p>Again, multiple regression allows us to control for the effects of multiple predictors on the outcome, and we are left with the unique effect of a predictor when controlling for other predictors. In this case, the outcome variable will be <code>phq9_p</code>, and the predictor variables will be <code>gender</code> (categorical variable) and <code>income_ratio</code> (continuous variable).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># fit5 &lt;- glm(</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="co">#   formula = phq9_p ~ gender + income_ratio, </span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="co">#   family = binomial(link = "logit"), </span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="co">#   weights = phq9_max,</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a><span class="co">#   data = depression2</span></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a><span class="co"># )</span></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a><span class="co"># </span></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a><span class="co"># model_parameters(fit5) |&gt; print_md()</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="paramter-table-interpretation-log-odds" class="level3" data-number="5.3.1">
<h3 data-number="5.3.1" class="anchored" data-anchor-id="paramter-table-interpretation-log-odds"><span class="header-section-number">5.3.1</span> Paramter Table Interpretation (Log-odds)</h3>
<blockquote class="blockquote">
<p>The intercept is the average log-odds of scoring higher on the PHQ-9 for women, while accounting for the effect of <code>income_ratio</code>. In this case, women have a average log odds of -1.44 indiciating that they are less likely to score higher on the PHQ-9 (since it is a log odds less than 0).</p>
</blockquote>
<blockquote class="blockquote">
<p>Men have a 0.54 decrease in the log-odds of suriving relative to women while accounting for the effect of <code>income_ratio</code> (i.e., they have a worse chance of scoring higher so they have less chance of being severely depressed).</p>
</blockquote>
<blockquote class="blockquote">
<p>Because the intercept was significant, there was a significant difference between for women in the log odds versus 0, <span class="math inline">\(p&lt;0.001\)</span>. In addition, the difference in log-odds between men and women was significant, <span class="math inline">\(p&lt;0.001\)</span>.</p>
</blockquote>
<blockquote class="blockquote">
<p>Lastly, while controlling for the effect of <code>gender</code>, a one unit increase in <code>income_ratio</code> was significantly related to a 0.14 decrease in the log-odds of scoring one-unit higher on the PHQ-9.</p>
</blockquote>
</section>
<section id="parameter-table-interpretation-odds-ratio" class="level3" data-number="5.3.2">
<h3 data-number="5.3.2" class="anchored" data-anchor-id="parameter-table-interpretation-odds-ratio"><span class="header-section-number">5.3.2</span> Parameter Table Interpretation (Odds Ratio)</h3>
<p>We can also consider the results in odds ratio by using the “exponentiate” argument in <code>model_paramters()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co">#model_parameters(fit5, exponentiate = TRUE) |&gt; print_md()</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<blockquote class="blockquote">
<p>The intercept is the average odds of scoring higher on the PHQ-9 for women, while accounting for the effect of <code>income_ratio</code>. In this case, women have a average odds of 0.24 indiciating that they are less likely to score higher on the PHQ-9 (since it is a log odds ratio than 1).</p>
</blockquote>
<blockquote class="blockquote">
<p>Men have a 0.40 (because 1 - 0.60 = 0.40) decrease in the odds of suriving relative to women while accounting for the effect of <code>income_ratio</code> (i.e., they have a worse chance of scoring higher so they have less chance of being severely depressed).</p>
</blockquote>
<blockquote class="blockquote">
<p>Because the intercept was significant, there was a significant difference between for women in the odds versus 1, <span class="math inline">\(p&lt;0.001\)</span>. In addition, the difference in odds ratio between men and women was significant, <span class="math inline">\(p&lt;0.001\)</span>.</p>
</blockquote>
<blockquote class="blockquote">
<p>Lastly, while controlling for the effect of <code>gender</code>, a one unit increase in <code>income_ratio</code> was significantly related to a 0.13 decrease in the odds of scoring one-unit higher on the PHQ-9.</p>
</blockquote>


</section>
</section>
</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>When the parameter table is in odds, the significance test is applied to see differences from an odds value of 1. This is because, again, an odds value of 1 means that an event occurring versus not occurring is equally likely.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./binary-regression.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Binary Regression</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./linear-models.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Linear models</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">Introduction to Generalized Linear Modeling was written by Aaron Matthew Simmons and Jeffrey M. Girard.</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">This book was built with <a href="https://quarto.org/">Quarto</a>.</div>
  </div>
</footer>



</body></html>